services:
  app:
    build: .
    image: onlystudents/onlystudents:latest
    ports:
      - ${PORT}:8080
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      dragonfly:
        condition: service_started

  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    ulimits:
      memlock: -1

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_DATABASE}"]
      interval: 5s
      timeout: 5s
      retries: 10
