name: PR Checks

on:
  pull_request:
    branches:
      - main

jobs:
  frontend:
    if: forgejo.event.pull_request.head.repo.full_name == forgejo.repository
    runs-on: bun

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        working-directory: frontend
        run: bun install --frozen-lockfile

      - name: Check for vulnerabilities
        working-directory: frontend
        run: bun audit --audit-level=high

      - name: Build
        working-directory: frontend
        run: bun run vite build

  backend:
    if: forgejo.event.pull_request.head.repo.full_name == forgejo.repository
    runs-on: go

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # gitleaks needs full history

      - name: Download dependencies
        run: go mod download -x

      - name: govulncheck
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          $(go env GOPATH)/bin/govulncheck -show verbose ./...
      - name: gosec
        run: |
          go install github.com/securego/gosec/v2/cmd/gosec@latest
          $(go env GOPATH)/bin/gosec -exclude=G104 --exclude-dir frontend --exclude-dir internal/db/store ./...
      - name: gitleaks
        run: |
          go install github.com/zricethezav/gitleaks/v8@latest
          $(go env GOPATH)/bin/gitleaks detect --source=. --redact --exit-code=1
      - name: go vet
        run: |
          go vet ./...

      - name: Build
        env:
          CGO_ENABLED: 0
        run: go build -v -o app .
