// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: absences.sql

package db_queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getStudentAbsences = `-- name: GetStudentAbsences :many
SELECT
    a.id,
    COALESCE(cs.subject_name, s.subject_name) AS subject,
    s.code AS subject_code,
    CONCAT(t.first_name, ' ', t.last_name) AS teacher,
    a.date,
    a.type,
    a.justified,
    a.note,
    CONCAT(v.first_name, ' ', v.last_name) AS verified_by
FROM absences a
LEFT JOIN base_schedule bs ON bs.id = a.lesson_id
LEFT JOIN subjects s ON s.id = bs.subject_id
LEFT JOIN custom_subjects cs ON cs.id = bs.custom_subject_id
LEFT JOIN teachers t ON t.id = bs.teacher_id
LEFT JOIN teachers v ON v.id = a.verified_by
WHERE a.student_id = $1
ORDER BY a.date, COALESCE(cs.subject_name, s.subject_name), a.id
`

type GetStudentAbsencesRow struct {
	ID          int64
	Subject     string
	SubjectCode pgtype.Text
	Teacher     interface{}
	Date        pgtype.Date
	Type        string
	Justified   bool
	Note        pgtype.Text
	VerifiedBy  interface{}
}

func (q *Queries) GetStudentAbsences(ctx context.Context, studentID int32) ([]GetStudentAbsencesRow, error) {
	rows, err := q.db.Query(ctx, getStudentAbsences, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStudentAbsencesRow
	for rows.Next() {
		var i GetStudentAbsencesRow
		if err := rows.Scan(
			&i.ID,
			&i.Subject,
			&i.SubjectCode,
			&i.Teacher,
			&i.Date,
			&i.Type,
			&i.Justified,
			&i.Note,
			&i.VerifiedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTeacherAbsences = `-- name: GetTeacherAbsences :many
SELECT
    a.id,
    CONCAT(st.first_name, ' ', st.last_name) AS student,
    COALESCE(cs.subject_name, s.subject_name) AS subject,
    s.code AS subject_code,
    a.date,
    a.type,
    a.justified,
    a.note,
    CONCAT(v.first_name, ' ', v.last_name) AS verified_by
FROM absences a
JOIN students st ON st.id = a.student_id
LEFT JOIN base_schedule bs ON bs.id = a.lesson_id
LEFT JOIN subjects s ON s.id = bs.subject_id
LEFT JOIN custom_subjects cs ON cs.id = bs.custom_subject_id
LEFT JOIN teachers t ON t.id = bs.teacher_id
LEFT JOIN teachers v ON v.id = a.verified_by
WHERE t.id = $1
ORDER BY a.date, st.last_name, st.first_name, a.id
`

type GetTeacherAbsencesRow struct {
	ID          int64
	Student     interface{}
	Subject     string
	SubjectCode pgtype.Text
	Date        pgtype.Date
	Type        string
	Justified   bool
	Note        pgtype.Text
	VerifiedBy  interface{}
}

func (q *Queries) GetTeacherAbsences(ctx context.Context, id int32) ([]GetTeacherAbsencesRow, error) {
	rows, err := q.db.Query(ctx, getTeacherAbsences, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTeacherAbsencesRow
	for rows.Next() {
		var i GetTeacherAbsencesRow
		if err := rows.Scan(
			&i.ID,
			&i.Student,
			&i.Subject,
			&i.SubjectCode,
			&i.Date,
			&i.Type,
			&i.Justified,
			&i.Note,
			&i.VerifiedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
