// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package db_queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :exec
INSERT INTO accounts (id,role,student_id,teacher_id,guardian_id,email_address,email_verified,theme,lang,pfp_url,nickname) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type CreateAccountParams struct {
	ID            pgtype.UUID
	Role          string
	StudentID     pgtype.Int4
	TeacherID     pgtype.Int4
	GuardianID    pgtype.Int4
	EmailAddress  pgtype.Text
	EmailVerified bool
	Theme         string
	Lang          string
	PfpUrl        string
	Nickname      string
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) error {
	_, err := q.db.Exec(ctx, createAccount,
		arg.ID,
		arg.Role,
		arg.StudentID,
		arg.TeacherID,
		arg.GuardianID,
		arg.EmailAddress,
		arg.EmailVerified,
		arg.Theme,
		arg.Lang,
		arg.PfpUrl,
		arg.Nickname,
	)
	return err
}

const getAccountByGuardianID = `-- name: GetAccountByGuardianID :one
SELECT id, role, student_id, teacher_id, guardian_id, email_address, email_verified, theme, lang, pfp_url, nickname, preferences FROM accounts WHERE guardian_id = $1 AND role = 'guardian'
`

func (q *Queries) GetAccountByGuardianID(ctx context.Context, guardianID pgtype.Int4) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByGuardianID, guardianID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.StudentID,
		&i.TeacherID,
		&i.GuardianID,
		&i.EmailAddress,
		&i.EmailVerified,
		&i.Theme,
		&i.Lang,
		&i.PfpUrl,
		&i.Nickname,
		&i.Preferences,
	)
	return i, err
}

const getAccountByStudentID = `-- name: GetAccountByStudentID :one
SELECT id, role, student_id, teacher_id, guardian_id, email_address, email_verified, theme, lang, pfp_url, nickname, preferences FROM accounts WHERE student_id = $1 AND role = 'student'
`

func (q *Queries) GetAccountByStudentID(ctx context.Context, studentID pgtype.Int4) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByStudentID, studentID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.StudentID,
		&i.TeacherID,
		&i.GuardianID,
		&i.EmailAddress,
		&i.EmailVerified,
		&i.Theme,
		&i.Lang,
		&i.PfpUrl,
		&i.Nickname,
		&i.Preferences,
	)
	return i, err
}

const getAccountByTeacherID = `-- name: GetAccountByTeacherID :one
SELECT id, role, student_id, teacher_id, guardian_id, email_address, email_verified, theme, lang, pfp_url, nickname, preferences FROM accounts WHERE teacher_id = $1 AND role = 'teacher'
`

func (q *Queries) GetAccountByTeacherID(ctx context.Context, teacherID pgtype.Int4) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByTeacherID, teacherID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.StudentID,
		&i.TeacherID,
		&i.GuardianID,
		&i.EmailAddress,
		&i.EmailVerified,
		&i.Theme,
		&i.Lang,
		&i.PfpUrl,
		&i.Nickname,
		&i.Preferences,
	)
	return i, err
}

const getAccountByUUID = `-- name: GetAccountByUUID :one
SELECT id, role, student_id, teacher_id, guardian_id, email_address, email_verified, theme, lang, pfp_url, nickname, preferences FROM accounts WHERE id = $1
`

func (q *Queries) GetAccountByUUID(ctx context.Context, id pgtype.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByUUID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.StudentID,
		&i.TeacherID,
		&i.GuardianID,
		&i.EmailAddress,
		&i.EmailVerified,
		&i.Theme,
		&i.Lang,
		&i.PfpUrl,
		&i.Nickname,
		&i.Preferences,
	)
	return i, err
}

const updateEmailGuardian = `-- name: UpdateEmailGuardian :exec
UPDATE accounts SET email_address = $1, email_verified = false WHERE guardian_id = $2 AND role = 'guardian'
`

type UpdateEmailGuardianParams struct {
	EmailAddress pgtype.Text
	GuardianID   pgtype.Int4
}

func (q *Queries) UpdateEmailGuardian(ctx context.Context, arg UpdateEmailGuardianParams) error {
	_, err := q.db.Exec(ctx, updateEmailGuardian, arg.EmailAddress, arg.GuardianID)
	return err
}

const updateEmailStudent = `-- name: UpdateEmailStudent :exec
UPDATE accounts SET email_address = $1, email_verified = false WHERE student_id = $2 AND role = 'student'
`

type UpdateEmailStudentParams struct {
	EmailAddress pgtype.Text
	StudentID    pgtype.Int4
}

func (q *Queries) UpdateEmailStudent(ctx context.Context, arg UpdateEmailStudentParams) error {
	_, err := q.db.Exec(ctx, updateEmailStudent, arg.EmailAddress, arg.StudentID)
	return err
}

const updateEmailTeacher = `-- name: UpdateEmailTeacher :exec
UPDATE accounts SET email_address = $1, email_verified = false WHERE teacher_id = $2 AND role = 'teacher'
`

type UpdateEmailTeacherParams struct {
	EmailAddress pgtype.Text
	TeacherID    pgtype.Int4
}

func (q *Queries) UpdateEmailTeacher(ctx context.Context, arg UpdateEmailTeacherParams) error {
	_, err := q.db.Exec(ctx, updateEmailTeacher, arg.EmailAddress, arg.TeacherID)
	return err
}

const updateLangGuardian = `-- name: UpdateLangGuardian :exec
UPDATE accounts SET lang = $1 WHERE guardian_id = $2 AND role = 'guardian'
`

type UpdateLangGuardianParams struct {
	Lang       string
	GuardianID pgtype.Int4
}

func (q *Queries) UpdateLangGuardian(ctx context.Context, arg UpdateLangGuardianParams) error {
	_, err := q.db.Exec(ctx, updateLangGuardian, arg.Lang, arg.GuardianID)
	return err
}

const updateLangStudent = `-- name: UpdateLangStudent :exec
UPDATE accounts SET lang = $1 WHERE student_id = $2 AND role = 'student'
`

type UpdateLangStudentParams struct {
	Lang      string
	StudentID pgtype.Int4
}

func (q *Queries) UpdateLangStudent(ctx context.Context, arg UpdateLangStudentParams) error {
	_, err := q.db.Exec(ctx, updateLangStudent, arg.Lang, arg.StudentID)
	return err
}

const updateLangTeacher = `-- name: UpdateLangTeacher :exec
UPDATE accounts SET lang = $1 WHERE teacher_id = $2 AND role = 'teacher'
`

type UpdateLangTeacherParams struct {
	Lang      string
	TeacherID pgtype.Int4
}

func (q *Queries) UpdateLangTeacher(ctx context.Context, arg UpdateLangTeacherParams) error {
	_, err := q.db.Exec(ctx, updateLangTeacher, arg.Lang, arg.TeacherID)
	return err
}

const updateNicknameGuardian = `-- name: UpdateNicknameGuardian :exec
UPDATE accounts SET nickname = $1 WHERE guardian_id = $2 AND role = 'guardian'
`

type UpdateNicknameGuardianParams struct {
	Nickname   string
	GuardianID pgtype.Int4
}

func (q *Queries) UpdateNicknameGuardian(ctx context.Context, arg UpdateNicknameGuardianParams) error {
	_, err := q.db.Exec(ctx, updateNicknameGuardian, arg.Nickname, arg.GuardianID)
	return err
}

const updateNicknameStudent = `-- name: UpdateNicknameStudent :exec
UPDATE accounts SET nickname = $1 WHERE student_id = $2 AND role = 'student'
`

type UpdateNicknameStudentParams struct {
	Nickname  string
	StudentID pgtype.Int4
}

func (q *Queries) UpdateNicknameStudent(ctx context.Context, arg UpdateNicknameStudentParams) error {
	_, err := q.db.Exec(ctx, updateNicknameStudent, arg.Nickname, arg.StudentID)
	return err
}

const updateNicknameTeacher = `-- name: UpdateNicknameTeacher :exec
UPDATE accounts SET nickname = $1 WHERE teacher_id = $2 AND role = 'teacher'
`

type UpdateNicknameTeacherParams struct {
	Nickname  string
	TeacherID pgtype.Int4
}

func (q *Queries) UpdateNicknameTeacher(ctx context.Context, arg UpdateNicknameTeacherParams) error {
	_, err := q.db.Exec(ctx, updateNicknameTeacher, arg.Nickname, arg.TeacherID)
	return err
}

const updatePreferencesGuardian = `-- name: UpdatePreferencesGuardian :exec
UPDATE accounts SET preferences = $1 WHERE guardian_id = $2 AND role = 'guardian'
`

type UpdatePreferencesGuardianParams struct {
	Preferences int32
	GuardianID  pgtype.Int4
}

func (q *Queries) UpdatePreferencesGuardian(ctx context.Context, arg UpdatePreferencesGuardianParams) error {
	_, err := q.db.Exec(ctx, updatePreferencesGuardian, arg.Preferences, arg.GuardianID)
	return err
}

const updatePreferencesStudent = `-- name: UpdatePreferencesStudent :exec
UPDATE accounts SET preferences = $1 WHERE student_id = $2 AND role = 'student'
`

type UpdatePreferencesStudentParams struct {
	Preferences int32
	StudentID   pgtype.Int4
}

func (q *Queries) UpdatePreferencesStudent(ctx context.Context, arg UpdatePreferencesStudentParams) error {
	_, err := q.db.Exec(ctx, updatePreferencesStudent, arg.Preferences, arg.StudentID)
	return err
}

const updatePreferencesTeacher = `-- name: UpdatePreferencesTeacher :exec
UPDATE accounts SET preferences = $1 WHERE teacher_id = $2 AND role = 'teacher'
`

type UpdatePreferencesTeacherParams struct {
	Preferences int32
	TeacherID   pgtype.Int4
}

func (q *Queries) UpdatePreferencesTeacher(ctx context.Context, arg UpdatePreferencesTeacherParams) error {
	_, err := q.db.Exec(ctx, updatePreferencesTeacher, arg.Preferences, arg.TeacherID)
	return err
}

const updateThemeGuardian = `-- name: UpdateThemeGuardian :exec
UPDATE accounts SET theme = $1 WHERE guardian_id = $2 AND role = 'guardian'
`

type UpdateThemeGuardianParams struct {
	Theme      string
	GuardianID pgtype.Int4
}

func (q *Queries) UpdateThemeGuardian(ctx context.Context, arg UpdateThemeGuardianParams) error {
	_, err := q.db.Exec(ctx, updateThemeGuardian, arg.Theme, arg.GuardianID)
	return err
}

const updateThemeStudent = `-- name: UpdateThemeStudent :exec
UPDATE accounts SET theme = $1 WHERE student_id = $2 AND role = 'student'
`

type UpdateThemeStudentParams struct {
	Theme     string
	StudentID pgtype.Int4
}

func (q *Queries) UpdateThemeStudent(ctx context.Context, arg UpdateThemeStudentParams) error {
	_, err := q.db.Exec(ctx, updateThemeStudent, arg.Theme, arg.StudentID)
	return err
}

const updateThemeTeacher = `-- name: UpdateThemeTeacher :exec
UPDATE accounts SET theme = $1 WHERE teacher_id = $2 AND role = 'teacher'
`

type UpdateThemeTeacherParams struct {
	Theme     string
	TeacherID pgtype.Int4
}

func (q *Queries) UpdateThemeTeacher(ctx context.Context, arg UpdateThemeTeacherParams) error {
	_, err := q.db.Exec(ctx, updateThemeTeacher, arg.Theme, arg.TeacherID)
	return err
}

const verifyEmailGuardian = `-- name: VerifyEmailGuardian :exec
UPDATE accounts SET email_verified = true WHERE guardian_id = $1 AND role = 'guardian'
`

func (q *Queries) VerifyEmailGuardian(ctx context.Context, guardianID pgtype.Int4) error {
	_, err := q.db.Exec(ctx, verifyEmailGuardian, guardianID)
	return err
}

const verifyEmailStudent = `-- name: VerifyEmailStudent :exec
UPDATE accounts SET email_verified = true WHERE student_id = $1 AND role = 'student'
`

func (q *Queries) VerifyEmailStudent(ctx context.Context, studentID pgtype.Int4) error {
	_, err := q.db.Exec(ctx, verifyEmailStudent, studentID)
	return err
}

const verifyEmailTeacher = `-- name: VerifyEmailTeacher :exec
UPDATE accounts SET email_verified = true WHERE teacher_id = $1 AND role = 'teacher'
`

func (q *Queries) VerifyEmailTeacher(ctx context.Context, teacherID pgtype.Int4) error {
	_, err := q.db.Exec(ctx, verifyEmailTeacher, teacherID)
	return err
}
