// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package db_queries

import (
	"context"
)

const getAdminDebugData = `-- name: GetAdminDebugData :one
SELECT
  (SELECT COUNT(*) FROM accounts) AS account_count,
  (SELECT COUNT(*) FROM schools) AS school_count,
  (SELECT COUNT(*) FROM students) AS student_count,
  (SELECT COUNT(*) FROM teachers) AS teacher_count,
  (SELECT COUNT(*) FROM guardians) AS guardian_count
`

type GetAdminDebugDataRow struct {
	AccountCount  int64
	SchoolCount   int64
	StudentCount  int64
	TeacherCount  int64
	GuardianCount int64
}

func (q *Queries) GetAdminDebugData(ctx context.Context) (GetAdminDebugDataRow, error) {
	row := q.db.QueryRow(ctx, getAdminDebugData)
	var i GetAdminDebugDataRow
	err := row.Scan(
		&i.AccountCount,
		&i.SchoolCount,
		&i.StudentCount,
		&i.TeacherCount,
		&i.GuardianCount,
	)
	return i, err
}
