// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exams.sql

package db_queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addExam = `-- name: AddExam :exec
INSERT INTO exams (class_subjects_id, teacher_id, title, description, date, start_time, end_time, room_id) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type AddExamParams struct {
	ClassSubjectsID int32
	TeacherID       int32
	Title           string
	Description     pgtype.Text
	Date            pgtype.Date
	StartTime       pgtype.Time
	EndTime         pgtype.Time
	RoomID          pgtype.Int4
}

func (q *Queries) AddExam(ctx context.Context, arg AddExamParams) error {
	_, err := q.db.Exec(ctx, addExam,
		arg.ClassSubjectsID,
		arg.TeacherID,
		arg.Title,
		arg.Description,
		arg.Date,
		arg.StartTime,
		arg.EndTime,
		arg.RoomID,
	)
	return err
}

const editExam = `-- name: EditExam :exec
UPDATE exams SET class_subjects_id = $2, teacher_id = $3, title = $4, description = $5, date = $6, start_time = $7, end_time = $8, room_id = $9 WHERE id = $1
`

type EditExamParams struct {
	ID              int64
	ClassSubjectsID int32
	TeacherID       int32
	Title           string
	Description     pgtype.Text
	Date            pgtype.Date
	StartTime       pgtype.Time
	EndTime         pgtype.Time
	RoomID          pgtype.Int4
}

func (q *Queries) EditExam(ctx context.Context, arg EditExamParams) error {
	_, err := q.db.Exec(ctx, editExam,
		arg.ID,
		arg.ClassSubjectsID,
		arg.TeacherID,
		arg.Title,
		arg.Description,
		arg.Date,
		arg.StartTime,
		arg.EndTime,
		arg.RoomID,
	)
	return err
}

const getStudentExams = `-- name: GetStudentExams :many
SELECT
    e.id,
    s.subject_name AS subject,
    s.code AS subject_code,
    CONCAT(t.first_name, ' ', t.last_name) AS teacher,
    e.title,
    e.description,
    e.date,
    e.start_time,
    e.end_time,
    r.name AS room
FROM exams e
JOIN subjects s ON s.id = e.class_subjects_id
JOIN teachers t ON t.id = e.teacher_id
LEFT JOIN rooms r ON r.id = e.room_id
WHERE e.class_subjects_id IN (
    SELECT bs.subject_id
    FROM base_schedule bs
    JOIN group_members gm ON gm.group_id = bs.group_id
    WHERE gm.student_id = $1
      AND bs.subject_id IS NOT NULL
)
ORDER BY e.date, e.start_time
`

type GetStudentExamsRow struct {
	ID          int64
	Subject     string
	SubjectCode pgtype.Text
	Teacher     interface{}
	Title       string
	Description pgtype.Text
	Date        pgtype.Date
	StartTime   pgtype.Time
	EndTime     pgtype.Time
	Room        pgtype.Text
}

func (q *Queries) GetStudentExams(ctx context.Context, studentID int32) ([]GetStudentExamsRow, error) {
	rows, err := q.db.Query(ctx, getStudentExams, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStudentExamsRow
	for rows.Next() {
		var i GetStudentExamsRow
		if err := rows.Scan(
			&i.ID,
			&i.Subject,
			&i.SubjectCode,
			&i.Teacher,
			&i.Title,
			&i.Description,
			&i.Date,
			&i.StartTime,
			&i.EndTime,
			&i.Room,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
