// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: grades.sql

package db_queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addFinalGrade = `-- name: AddFinalGrade :exec
INSERT INTO final_grades (student_id, class_subjects_id, term_id, teacher_id, value) VALUES ($1, $2, $3, $4, $5)
`

type AddFinalGradeParams struct {
	StudentID       int32
	ClassSubjectsID int32
	TermID          int32
	TeacherID       int32
	Value           int16
}

func (q *Queries) AddFinalGrade(ctx context.Context, arg AddFinalGradeParams) error {
	_, err := q.db.Exec(ctx, addFinalGrade,
		arg.StudentID,
		arg.ClassSubjectsID,
		arg.TermID,
		arg.TeacherID,
		arg.Value,
	)
	return err
}

const addGrade = `-- name: AddGrade :exec
INSERT INTO grades (student_id, class_subjects_id, teacher_id, term_id, grade_type_id, value, date, note) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type AddGradeParams struct {
	StudentID       int32
	ClassSubjectsID int32
	TeacherID       int32
	TermID          int32
	GradeTypeID     int32
	Value           int16
	Date            pgtype.Date
	Note            pgtype.Text
}

func (q *Queries) AddGrade(ctx context.Context, arg AddGradeParams) error {
	_, err := q.db.Exec(ctx, addGrade,
		arg.StudentID,
		arg.ClassSubjectsID,
		arg.TeacherID,
		arg.TermID,
		arg.GradeTypeID,
		arg.Value,
		arg.Date,
		arg.Note,
	)
	return err
}

const editFinalGrade = `-- name: EditFinalGrade :exec
UPDATE final_grades SET class_subjects_id = $2, term_id = $3, teacher_id = $4, value = $5 WHERE id = $1
`

type EditFinalGradeParams struct {
	ID              int64
	ClassSubjectsID int32
	TermID          int32
	TeacherID       int32
	Value           int16
}

func (q *Queries) EditFinalGrade(ctx context.Context, arg EditFinalGradeParams) error {
	_, err := q.db.Exec(ctx, editFinalGrade,
		arg.ID,
		arg.ClassSubjectsID,
		arg.TermID,
		arg.TeacherID,
		arg.Value,
	)
	return err
}

const editGrade = `-- name: EditGrade :exec
UPDATE grades SET class_subjects_id = $2, teacher_id = $3, term_id = $4, grade_type_id = $5, value = $6, date = $7, note = $8 WHERE id = $1
`

type EditGradeParams struct {
	ID              int64
	ClassSubjectsID int32
	TeacherID       int32
	TermID          int32
	GradeTypeID     int32
	Value           int16
	Date            pgtype.Date
	Note            pgtype.Text
}

func (q *Queries) EditGrade(ctx context.Context, arg EditGradeParams) error {
	_, err := q.db.Exec(ctx, editGrade,
		arg.ID,
		arg.ClassSubjectsID,
		arg.TeacherID,
		arg.TermID,
		arg.GradeTypeID,
		arg.Value,
		arg.Date,
		arg.Note,
	)
	return err
}

const getStudentFinalGrades = `-- name: GetStudentFinalGrades :many
SELECT
    fg.id,
    COALESCE(cs.subject_name, s.subject_name) AS subject,
    s.code AS subject_code,
    CONCAT(t.first_name, ' ', t.last_name) AS teacher,
    ter.name AS term,
    fg.value
FROM final_grades fg
JOIN class_subjects csub ON csub.id = fg.class_subjects_id
LEFT JOIN subjects s ON s.id = csub.subject_id
LEFT JOIN custom_subjects cs ON cs.id = csub.custom_subject_id
JOIN teachers t ON t.id = fg.teacher_id
JOIN terms ter ON ter.id = fg.term_id
WHERE fg.student_id = $1
ORDER BY fg.term_id, COALESCE(cs.subject_name, s.subject_name)
`

type GetStudentFinalGradesRow struct {
	ID          int64
	Subject     string
	SubjectCode pgtype.Text
	Teacher     interface{}
	Term        string
	Value       int16
}

func (q *Queries) GetStudentFinalGrades(ctx context.Context, studentID int32) ([]GetStudentFinalGradesRow, error) {
	rows, err := q.db.Query(ctx, getStudentFinalGrades, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStudentFinalGradesRow
	for rows.Next() {
		var i GetStudentFinalGradesRow
		if err := rows.Scan(
			&i.ID,
			&i.Subject,
			&i.SubjectCode,
			&i.Teacher,
			&i.Term,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStudentGrades = `-- name: GetStudentGrades :many
SELECT
    g.id,
    COALESCE(cs.subject_name, s.subject_name) AS subject,
    s.code AS subject_code,
    CONCAT(t.first_name, ' ', t.last_name) AS teacher,
    ter.name AS term,
    gt.name AS type,
    g.value,
    g.date,
    g.note
FROM grades g
JOIN class_subjects csub ON csub.id = g.class_subjects_id
LEFT JOIN subjects s ON s.id = csub.subject_id
LEFT JOIN custom_subjects cs ON cs.id = csub.custom_subject_id
JOIN teachers t ON t.id = g.teacher_id
JOIN terms ter ON ter.id = g.term_id
JOIN grade_types gt ON gt.id = g.grade_type_id
WHERE g.student_id = $1
ORDER BY g.term_id, COALESCE(cs.subject_name, s.subject_name), g.date
`

type GetStudentGradesRow struct {
	ID          int64
	Subject     string
	SubjectCode pgtype.Text
	Teacher     interface{}
	Term        string
	Type        string
	Value       int16
	Date        pgtype.Date
	Note        pgtype.Text
}

func (q *Queries) GetStudentGrades(ctx context.Context, studentID int32) ([]GetStudentGradesRow, error) {
	rows, err := q.db.Query(ctx, getStudentGrades, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStudentGradesRow
	for rows.Next() {
		var i GetStudentGradesRow
		if err := rows.Scan(
			&i.ID,
			&i.Subject,
			&i.SubjectCode,
			&i.Teacher,
			&i.Term,
			&i.Type,
			&i.Value,
			&i.Date,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
