// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: grades.sql

package db_queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getStudentFinalGrades = `-- name: GetStudentFinalGrades :many
SELECT
    fg.id,
    s.subject_name AS subject,
    s.code AS subject_code,
    CONCAT(t.first_name, ' ', t.last_name) AS teacher,
    ter.name AS term,
    fg.value
FROM final_grades fg
JOIN subjects s ON s.id = fg.class_subjects_id
JOIN teachers t ON t.id = fg.teacher_id
JOIN terms ter ON ter.id = fg.term_id
WHERE fg.student_id = $1
ORDER BY fg.term_id, s.subject_name
`

type GetStudentFinalGradesRow struct {
	ID          int64
	Subject     string
	SubjectCode pgtype.Text
	Teacher     interface{}
	Term        string
	Value       int16
}

func (q *Queries) GetStudentFinalGrades(ctx context.Context, studentID int32) ([]GetStudentFinalGradesRow, error) {
	rows, err := q.db.Query(ctx, getStudentFinalGrades, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStudentFinalGradesRow
	for rows.Next() {
		var i GetStudentFinalGradesRow
		if err := rows.Scan(
			&i.ID,
			&i.Subject,
			&i.SubjectCode,
			&i.Teacher,
			&i.Term,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStudentGrades = `-- name: GetStudentGrades :many
SELECT
    g.id,
    s.subject_name AS subject,
    s.code AS subject_code,
    CONCAT(t.first_name, ' ', t.last_name) AS teacher,
    ter.name AS term,
    gt.name AS type,
    g.value,
    g.date,
    g.note
FROM grades g
JOIN subjects s ON s.id = g.class_subjects_id
JOIN teachers t ON t.id = g.teacher_id
JOIN terms ter ON ter.id = g.term_id
JOIN grade_types gt ON gt.id = g.grade_type_id
WHERE g.student_id = $1
ORDER BY g.term_id, s.subject_name, g.date
`

type GetStudentGradesRow struct {
	ID          int64
	Subject     string
	SubjectCode pgtype.Text
	Teacher     interface{}
	Term        string
	Type        string
	Value       int16
	Date        pgtype.Date
	Note        pgtype.Text
}

func (q *Queries) GetStudentGrades(ctx context.Context, studentID int32) ([]GetStudentGradesRow, error) {
	rows, err := q.db.Query(ctx, getStudentGrades, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStudentGradesRow
	for rows.Next() {
		var i GetStudentGradesRow
		if err := rows.Scan(
			&i.ID,
			&i.Subject,
			&i.SubjectCode,
			&i.Teacher,
			&i.Term,
			&i.Type,
			&i.Value,
			&i.Date,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTeacherGrades = `-- name: GetTeacherGrades :many
SELECT
    g.id,
    s.subject_name AS subject,
    s.code AS subject_code,
    CONCAT(t.first_name, ' ', t.last_name) AS teacher,
    ter.name AS term,
    gt.name AS type,
    g.value,
    g.date,
    g.note
FROM grades g
JOIN subjects s ON s.id = g.class_subjects_id
JOIN teachers t ON t.id = g.teacher_id
JOIN terms ter ON ter.id = g.term_id
JOIN grade_types gt ON gt.id = g.grade_type_id
WHERE g.teacher_id = $1
ORDER BY g.term_id, s.subject_name, g.date
`

type GetTeacherGradesRow struct {
	ID          int64
	Subject     string
	SubjectCode pgtype.Text
	Teacher     interface{}
	Term        string
	Type        string
	Value       int16
	Date        pgtype.Date
	Note        pgtype.Text
}

func (q *Queries) GetTeacherGrades(ctx context.Context, teacherID int32) ([]GetTeacherGradesRow, error) {
	rows, err := q.db.Query(ctx, getTeacherGrades, teacherID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTeacherGradesRow
	for rows.Next() {
		var i GetTeacherGradesRow
		if err := rows.Scan(
			&i.ID,
			&i.Subject,
			&i.SubjectCode,
			&i.Teacher,
			&i.Term,
			&i.Type,
			&i.Value,
			&i.Date,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
