// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: groups.sql

package db_queries

import (
	"context"
)

const getClassByID = `-- name: GetClassByID :one
SELECT id, school_id, name, teacher_id, co_teacher_id, bell_id FROM classes WHERE id = $1
`

func (q *Queries) GetClassByID(ctx context.Context, id int32) (Class, error) {
	row := q.db.QueryRow(ctx, getClassByID, id)
	var i Class
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.Name,
		&i.TeacherID,
		&i.CoTeacherID,
		&i.BellID,
	)
	return i, err
}

const getGroupsByStudentID = `-- name: GetGroupsByStudentID :many
SELECT g.id, g.school_id, g.bell_id, g.group_name
FROM groups g
JOIN group_members gm ON gm.group_id = g.id AND gm.school_id = g.school_id
WHERE gm.student_id = $1 AND g.school_id = $2
ORDER BY g.group_name
`

type GetGroupsByStudentIDParams struct {
	StudentID int32
	SchoolID  int32
}

func (q *Queries) GetGroupsByStudentID(ctx context.Context, arg GetGroupsByStudentIDParams) ([]Group, error) {
	rows, err := q.db.Query(ctx, getGroupsByStudentID, arg.StudentID, arg.SchoolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.SchoolID,
			&i.BellID,
			&i.GroupName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
