// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: guardians.sql

package db_queries

import (
	"context"
)

const getGuardian = `-- name: GetGuardian :one
SELECT id, phone_number, first_name, last_name, birth_first_name, birth_last_name, birth_date, birth_city, birth_country, permament_address, temporary_address FROM guardians WHERE id = $1
`

func (q *Queries) GetGuardian(ctx context.Context, id int32) (Guardian, error) {
	row := q.db.QueryRow(ctx, getGuardian, id)
	var i Guardian
	err := row.Scan(
		&i.ID,
		&i.PhoneNumber,
		&i.FirstName,
		&i.LastName,
		&i.BirthFirstName,
		&i.BirthLastName,
		&i.BirthDate,
		&i.BirthCity,
		&i.BirthCountry,
		&i.PermamentAddress,
		&i.TemporaryAddress,
	)
	return i, err
}

const listGuardians = `-- name: ListGuardians :many
SELECT id, phone_number, first_name, last_name, birth_first_name, birth_last_name, birth_date, birth_city, birth_country, permament_address, temporary_address FROM guardians ORDER BY id
`

func (q *Queries) ListGuardians(ctx context.Context) ([]Guardian, error) {
	rows, err := q.db.Query(ctx, listGuardians)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Guardian
	for rows.Next() {
		var i Guardian
		if err := rows.Scan(
			&i.ID,
			&i.PhoneNumber,
			&i.FirstName,
			&i.LastName,
			&i.BirthFirstName,
			&i.BirthLastName,
			&i.BirthDate,
			&i.BirthCity,
			&i.BirthCountry,
			&i.PermamentAddress,
			&i.TemporaryAddress,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
