// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: homework.sql

package db_queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addHomework = `-- name: AddHomework :exec
INSERT INTO homework (class_subjects_id, teacher_id, title, description, due_date) VALUES ($1, $2, $3, $4, $5)
`

type AddHomeworkParams struct {
	ClassSubjectsID int32
	TeacherID       int32
	Title           string
	Description     pgtype.Text
	DueDate         pgtype.Date
}

func (q *Queries) AddHomework(ctx context.Context, arg AddHomeworkParams) error {
	_, err := q.db.Exec(ctx, addHomework,
		arg.ClassSubjectsID,
		arg.TeacherID,
		arg.Title,
		arg.Description,
		arg.DueDate,
	)
	return err
}

const addHomeworkSubmission = `-- name: AddHomeworkSubmission :exec
INSERT INTO homework_submissions (homework_id, student_id, content) VALUES ($1, $2, $3)
`

type AddHomeworkSubmissionParams struct {
	HomeworkID int32
	StudentID  int32
	Content    pgtype.Text
}

func (q *Queries) AddHomeworkSubmission(ctx context.Context, arg AddHomeworkSubmissionParams) error {
	_, err := q.db.Exec(ctx, addHomeworkSubmission, arg.HomeworkID, arg.StudentID, arg.Content)
	return err
}

const editHomework = `-- name: EditHomework :exec
UPDATE homework SET class_subjects_id = $2, teacher_id = $3, title = $4, description = $5, due_date = $6 WHERE id = $1
`

type EditHomeworkParams struct {
	ID              int64
	ClassSubjectsID int32
	TeacherID       int32
	Title           string
	Description     pgtype.Text
	DueDate         pgtype.Date
}

func (q *Queries) EditHomework(ctx context.Context, arg EditHomeworkParams) error {
	_, err := q.db.Exec(ctx, editHomework,
		arg.ID,
		arg.ClassSubjectsID,
		arg.TeacherID,
		arg.Title,
		arg.Description,
		arg.DueDate,
	)
	return err
}

const editHomeworkSubmission = `-- name: EditHomeworkSubmission :exec
UPDATE homework_submissions SET content = $2, graded_value = $3 WHERE homework_id = $1 AND student_id = $4
`

type EditHomeworkSubmissionParams struct {
	HomeworkID  int32
	Content     pgtype.Text
	GradedValue pgtype.Int2
	StudentID   int32
}

func (q *Queries) EditHomeworkSubmission(ctx context.Context, arg EditHomeworkSubmissionParams) error {
	_, err := q.db.Exec(ctx, editHomeworkSubmission,
		arg.HomeworkID,
		arg.Content,
		arg.GradedValue,
		arg.StudentID,
	)
	return err
}

const getStudentHomework = `-- name: GetStudentHomework :many
SELECT
    h.id,
    COALESCE(cs.subject_name, s.subject_name) AS subject,
    s.code AS subject_code,
    CONCAT(t.first_name, ' ', t.last_name) AS teacher,
    h.title,
    h.description,
    h.due_date,
    h.created_at,
    hs.submitted_at,
    hs.graded_value
FROM homework h
JOIN class_subjects csub ON csub.id = h.class_subjects_id
LEFT JOIN subjects s ON s.id = csub.subject_id
LEFT JOIN custom_subjects cs ON cs.id = csub.custom_subject_id
JOIN teachers t ON t.id = h.teacher_id
LEFT JOIN homework_submissions hs ON hs.homework_id = h.id AND hs.student_id = $1
WHERE csub.class_id = (
    SELECT st.classes_id
    FROM students st
    WHERE st.id = $1
)
ORDER BY h.due_date, h.created_at
`

type GetStudentHomeworkRow struct {
	ID          int64
	Subject     string
	SubjectCode pgtype.Text
	Teacher     interface{}
	Title       string
	Description pgtype.Text
	DueDate     pgtype.Date
	CreatedAt   pgtype.Timestamptz
	SubmittedAt pgtype.Timestamptz
	GradedValue pgtype.Int2
}

func (q *Queries) GetStudentHomework(ctx context.Context, studentID int32) ([]GetStudentHomeworkRow, error) {
	rows, err := q.db.Query(ctx, getStudentHomework, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStudentHomeworkRow
	for rows.Next() {
		var i GetStudentHomeworkRow
		if err := rows.Scan(
			&i.ID,
			&i.Subject,
			&i.SubjectCode,
			&i.Teacher,
			&i.Title,
			&i.Description,
			&i.DueDate,
			&i.CreatedAt,
			&i.SubmittedAt,
			&i.GradedValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
