// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db_queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Absence struct {
	ID              int64
	StudentID       int32
	LessonID        pgtype.Int4
	Date            pgtype.Date
	Type            string
	Justified       bool
	VerifiedBy      pgtype.Int4
	Note            pgtype.Text
	ClassSubjectsID pgtype.Int4
}

type Account struct {
	ID            pgtype.UUID
	Role          string
	StudentID     pgtype.Int4
	TeacherID     pgtype.Int4
	GuardianID    pgtype.Int4
	EmailAddress  pgtype.Text
	EmailVerified bool
	Theme         string
	Lang          string
	PfpUrl        string
	Nickname      string
	Preferences   int32
}

type AccountOpaque struct {
	AccountUuid          pgtype.UUID
	RegistrationRecord   []byte
	CredentialIdentifier []byte
	CreatedAt            pgtype.Date
	UpdatedAt            pgtype.Date
}

type Announcement struct {
	ID              int64
	AuthorAccountID pgtype.UUID
	SchoolID        pgtype.Int4
	ClassID         pgtype.Int4
	Title           string
	Body            string
	Pinned          bool
	CreatedAt       pgtype.Timestamptz
}

type BaseSchedule struct {
	ID              int32
	SchoolID        int32
	TeacherID       int32
	RoomID          int32
	DayOfWeek       int32
	LessonNum       int32
	GroupID         int32
	CustomSubject   bool
	SubjectID       pgtype.Int4
	CustomSubjectID pgtype.Int4
}

type BellSchedule struct {
	ID           int32
	SchoolID     int32
	TypeID       int32
	LessonNumber pgtype.Int4
	AtStart      pgtype.Time
	AtEnd        pgtype.Time
}

type BellScheduleType struct {
	ID       int32
	SchoolID int32
	Name     string
}

type Class struct {
	ID          int32
	SchoolID    int32
	Name        string
	TeacherID   int32
	CoTeacherID pgtype.Int4
	BellID      pgtype.Int4
}

type ClassSubject struct {
	ID              int32
	SchoolID        int32
	ClassID         int32
	SubjectID       pgtype.Int4
	CustomSubject   bool
	CustomSubjectID pgtype.Int4
	TeacherID       int32
}

type CustomSubject struct {
	ID          int32
	SchoolID    int32
	SubjectName string
}

type Exam struct {
	ID              int64
	ClassSubjectsID int32
	TeacherID       int32
	Title           string
	Description     pgtype.Text
	Date            pgtype.Date
	StartTime       pgtype.Time
	EndTime         pgtype.Time
	RoomID          pgtype.Int4
}

type FinalGrade struct {
	ID              int64
	StudentID       int32
	ClassSubjectsID int32
	TermID          int32
	TeacherID       int32
	Value           int16
}

type Grade struct {
	ID              int64
	StudentID       int32
	ClassSubjectsID int32
	TeacherID       int32
	TermID          int32
	GradeTypeID     int32
	Value           int16
	Date            pgtype.Date
	Note            pgtype.Text
}

type GradeType struct {
	ID       int32
	SchoolID int32
	Name     string
	Weight   int32
}

type Group struct {
	ID        int32
	SchoolID  int32
	BellID    int32
	GroupName string
}

type GroupMember struct {
	ID        int32
	SchoolID  int32
	GroupID   int32
	StudentID int32
}

type Guardian struct {
	ID               int32
	PhoneNumber      string
	FirstName        string
	LastName         string
	BirthFirstName   string
	BirthLastName    string
	BirthDate        pgtype.Date
	BirthCity        string
	BirthCountry     string
	PermamentAddress string
	TemporaryAddress string
}

type GuardianCitizenship struct {
	ID           int32
	UserID       int32
	DocumentType string
	Country      string
}

type GuardiansAccess struct {
	ID                  int32
	StudentID           int32
	GuardianID          int32
	LegalRepresentative bool
}

type Homework struct {
	ID              int64
	ClassSubjectsID int32
	TeacherID       int32
	Title           string
	Description     pgtype.Text
	DueDate         pgtype.Date
	CreatedAt       pgtype.Timestamptz
}

type HomeworkSubmission struct {
	ID          int64
	HomeworkID  int32
	StudentID   int32
	Content     pgtype.Text
	SubmittedAt pgtype.Timestamptz
	GradedValue pgtype.Int2
}

type LessonLog struct {
	ID         int64
	LessonID   int32
	Date       pgtype.Date
	TeacherID  int32
	Topic      pgtype.Text
	HomeworkID pgtype.Int4
	Conducted  bool
}

type Permission struct {
	ID           int32
	SchoolID     int32
	TeacherID    int32
	PermissionID int32
}

type PermissionType struct {
	ID          int32
	Name        string
	Description string
}

type Principal struct {
	ID        int32
	SchoolID  int32
	TeacherID int32
}

type Room struct {
	ID       int32
	SchoolID int32
	Name     string
	Capacity int32
}

type School struct {
	ID           int32
	Name         string
	ZipCode      string
	City         string
	AddressLine  string
	SchoolType   int32
	PrincipalID  int32
	PhoneNumber  string
	EmailAddress string
}

type SchoolType struct {
	ID   int32
	Name string
}

type SchoolYear struct {
	ID        int32
	SchoolID  int32
	Name      string
	StartDate pgtype.Date
	EndDate   pgtype.Date
	IsActive  bool
}

type Session struct {
	ID          pgtype.UUID
	AccountUuid pgtype.UUID
	CreatedAt   pgtype.Date
	LastSeenAt  pgtype.Date
}

type Student struct {
	ID                   int32
	IDNumber             int32
	SchoolID             int32
	PhoneNumber          pgtype.Text
	FirstName            string
	LastName             string
	BirthFirstName       string
	BirthLastName        string
	BirthDate            pgtype.Date
	BirthCity            string
	BirthCountry         string
	MotherBirthFirstName string
	MotherBirthLastName  string
	ClassesID            int32
	PermamentAddress     string
	TemporaryAddress     string
	TaxNumber            pgtype.Int4
	SsnNumber            int32
	BankName             string
	IbanOwner            string
	IbanNumber           string
	DocumentType         string
	DocumentNumber       string
}

type StudentCitizenship struct {
	ID           int32
	UserID       int32
	DocumentType string
	Country      string
}

type Subject struct {
	ID          int32
	SubjectName string
	Code        pgtype.Text
}

type Teacher struct {
	ID               int32
	PhoneNumber      string
	Username         string
	BirthFirstName   string
	BirthLastName    string
	BirthDate        pgtype.Date
	BirthCity        string
	BirthCountry     string
	PermamentAddress string
	TemporaryAddress string
	FirstName        string
	LastName         string
}

type TeacherCitizenship struct {
	ID           int32
	UserID       int32
	DocumentType string
	Country      string
}

type TeacherSchool struct {
	ID        int32
	TeacherID int32
	SchoolID  int32
}

type Term struct {
	ID            int32
	SchoolYearID  int32
	Name          string
	StartDate     pgtype.Date
	EndDate       pgtype.Date
	GradeDeadline pgtype.Date
	IsActive      bool
}

type TimeTable struct {
	ID                    int32
	SchoolID              int32
	TeacherID             int32
	RoomID                int32
	DayOfWeek             int32
	GroupID               int32
	CustomSubject         bool
	SubjectID             pgtype.Int4
	CustomSubjectID       pgtype.Int4
	ActualDate            pgtype.Date
	LessonNum             int32
	IsSubstitution        bool
	SubstitutionTeacherID pgtype.Int4
	Canceled              pgtype.Bool
}
