// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db_queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Class struct {
	ID          int32
	SchoolID    int32
	Name        string
	TeacherID   int32
	CoTeacherID pgtype.Int4
}

type Guardian struct {
	ID               int32
	EmailAddress     string
	PhoneNumber      string
	FirstName        string
	LastName         string
	BirthFirstName   string
	BirthLastName    string
	BirthDate        pgtype.Date
	BirthCity        string
	BirthCountry     string
	PermamentAddress string
	TemporaryAddress string
	PasswordHash     string
	PasswordSalt     string
}

type GuardianCitizenship struct {
	ID           int32
	UserID       int32
	DocumentType string
	Country      string
}

type GuardiansAccess struct {
	ID                  int32
	StudentID           int32
	GuardianID          int32
	LegalRepresentative bool
}

type School struct {
	ID           int32
	Name         string
	ZipCode      string
	City         string
	AddressLine  string
	SchoolType   int32
	PrincipalID  int32
	PhoneNumber  string
	EmailAddress string
}

type SchoolType struct {
	ID   int32
	Name string
}

type Student struct {
	ID                   int32
	IDNumber             int32
	SchoolID             int32
	PhoneNumber          pgtype.Text
	EmailAddress         pgtype.Text
	FirstName            string
	LastName             string
	BirthFirstName       string
	BirthLastName        string
	BirthDate            pgtype.Date
	BirthCity            string
	BirthCountry         string
	MotherBirthFirstName string
	MotherBirthLastName  string
	ClassesID            int32
	PermamentAddress     string
	TemporaryAddress     string
	TaxNumber            pgtype.Int4
	SsnNumber            int32
	BankName             string
	IbanOwner            string
	IbanNumber           string
	DocumentType         string
	DocumentNumber       string
	PasswordHash         string
	PasswordSalt         string
}

type StudentCitizenship struct {
	ID           int32
	UserID       int32
	DocumentType string
	Country      string
}

type Teacher struct {
	ID               int32
	EmailAddress     string
	PhoneNumber      string
	Username         string
	BirthFirstName   string
	BirthLastName    string
	BirthDate        pgtype.Date
	BirthCity        string
	BirthCountry     string
	PermamentAddress string
	TemporaryAddress string
}

type TeacherCitizenship struct {
	ID           int32
	UserID       int32
	DocumentType string
	Country      string
}

type TeacherSchool struct {
	ID        int32
	TeacherID int32
	SchoolID  int32
}
