// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: opaque.sql

package db_queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOpaqueRecord = `-- name: CreateOpaqueRecord :exec
INSERT INTO account_opaque (account_uuid, registration_record, credential_identifier, created_at, updated_at)
VALUES ($1, $2, $3, current_date, current_date)
ON CONFLICT (account_uuid) DO UPDATE
SET registration_record = EXCLUDED.registration_record,
    credential_identifier = EXCLUDED.credential_identifier,
    updated_at = current_date
`

type CreateOpaqueRecordParams struct {
	AccountUuid          pgtype.UUID
	RegistrationRecord   []byte
	CredentialIdentifier []byte
}

func (q *Queries) CreateOpaqueRecord(ctx context.Context, arg CreateOpaqueRecordParams) error {
	_, err := q.db.Exec(ctx, createOpaqueRecord, arg.AccountUuid, arg.RegistrationRecord, arg.CredentialIdentifier)
	return err
}

const getOpaqueRecord = `-- name: GetOpaqueRecord :one
SELECT account_uuid, registration_record, credential_identifier, created_at, updated_at FROM account_opaque WHERE account_uuid = $1
`

func (q *Queries) GetOpaqueRecord(ctx context.Context, accountUuid pgtype.UUID) (AccountOpaque, error) {
	row := q.db.QueryRow(ctx, getOpaqueRecord, accountUuid)
	var i AccountOpaque
	err := row.Scan(
		&i.AccountUuid,
		&i.RegistrationRecord,
		&i.CredentialIdentifier,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOpaqueRecord = `-- name: UpdateOpaqueRecord :exec
UPDATE account_opaque SET registration_record = $1, credential_identifier = $2, updated_at = current_date WHERE account_uuid = $3
`

type UpdateOpaqueRecordParams struct {
	RegistrationRecord   []byte
	CredentialIdentifier []byte
	AccountUuid          pgtype.UUID
}

func (q *Queries) UpdateOpaqueRecord(ctx context.Context, arg UpdateOpaqueRecordParams) error {
	_, err := q.db.Exec(ctx, updateOpaqueRecord, arg.RegistrationRecord, arg.CredentialIdentifier, arg.AccountUuid)
	return err
}
