// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: permission.sql

package db_queries

import (
	"context"
)

const checkPermission = `-- name: CheckPermission :one
SELECT EXISTS (SELECT 1 FROM permissions p JOIN permission_type pt ON pt.id = p.permission_id WHERE (pt.name = $1 OR pt.name = 'PRINCIPAL') AND p.teacher_id = $2)
`

type CheckPermissionParams struct {
	Name      string
	TeacherID int32
}

func (q *Queries) CheckPermission(ctx context.Context, arg CheckPermissionParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkPermission, arg.Name, arg.TeacherID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
