// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: schools.sql

package db_queries

import (
	"context"
)

const getSchool = `-- name: GetSchool :one
SELECT id, name, zip_code, city, address_line, school_type, principal_id, phone_number, email_address FROM schools WHERE id = $1
`

func (q *Queries) GetSchool(ctx context.Context, id int32) (School, error) {
	row := q.db.QueryRow(ctx, getSchool, id)
	var i School
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ZipCode,
		&i.City,
		&i.AddressLine,
		&i.SchoolType,
		&i.PrincipalID,
		&i.PhoneNumber,
		&i.EmailAddress,
	)
	return i, err
}

const listSchools = `-- name: ListSchools :many
SELECT id, name, zip_code, city, address_line, school_type, principal_id, phone_number, email_address FROM schools ORDER BY id
`

func (q *Queries) ListSchools(ctx context.Context) ([]School, error) {
	rows, err := q.db.Query(ctx, listSchools)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []School
	for rows.Next() {
		var i School
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ZipCode,
			&i.City,
			&i.AddressLine,
			&i.SchoolType,
			&i.PrincipalID,
			&i.PhoneNumber,
			&i.EmailAddress,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
