// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scope.sql

package db_queries

import (
	"context"
)

const checkPermission = `-- name: CheckPermission :one
SELECT EXISTS (SELECT 1 FROM permissions p JOIN permission_type pt ON pt.id = p.permission_id WHERE (pt.name = $1 OR pt.name = 'PRINCIPAL') AND p.teacher_id = $2 AND p.school_id = $3)
`

type CheckPermissionParams struct {
	Name      string
	TeacherID int32
	SchoolID  int32
}

func (q *Queries) CheckPermission(ctx context.Context, arg CheckPermissionParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkPermission, arg.Name, arg.TeacherID, arg.SchoolID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isTeacherSchoolMember = `-- name: IsTeacherSchoolMember :one
SELECT EXISTS (SELECT 1 from teacher_school WHERE teacher_id = $1 AND school_id = $2)
`

type IsTeacherSchoolMemberParams struct {
	TeacherID int32
	SchoolID  int32
}

func (q *Queries) IsTeacherSchoolMember(ctx context.Context, arg IsTeacherSchoolMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isTeacherSchoolMember, arg.TeacherID, arg.SchoolID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const teacherClassSubjectHasStudent = `-- name: TeacherClassSubjectHasStudent :one
SELECT EXISTS (
    SELECT 1
    FROM class_subjects cs
    JOIN students st ON st.classes_id = cs.class_id
    WHERE cs.id = $1
      AND cs.school_id = $2
      AND cs.teacher_id = $3
      AND st.id = $4
)
`

type TeacherClassSubjectHasStudentParams struct {
	ID        int32
	SchoolID  int32
	TeacherID int32
	ID_2      int32
}

func (q *Queries) TeacherClassSubjectHasStudent(ctx context.Context, arg TeacherClassSubjectHasStudentParams) (bool, error) {
	row := q.db.QueryRow(ctx, teacherClassSubjectHasStudent,
		arg.ID,
		arg.SchoolID,
		arg.TeacherID,
		arg.ID_2,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const teacherOwnsClassSubject = `-- name: TeacherOwnsClassSubject :one
SELECT EXISTS (
    SELECT 1
    FROM class_subjects cs
    WHERE cs.id = $1
      AND cs.school_id = $2
      AND cs.teacher_id = $3
)
`

type TeacherOwnsClassSubjectParams struct {
	ID        int32
	SchoolID  int32
	TeacherID int32
}

func (q *Queries) TeacherOwnsClassSubject(ctx context.Context, arg TeacherOwnsClassSubjectParams) (bool, error) {
	row := q.db.QueryRow(ctx, teacherOwnsClassSubject, arg.ID, arg.SchoolID, arg.TeacherID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const teacherTeachesStudent = `-- name: TeacherTeachesStudent :one
SELECT EXISTS (
    SELECT 1
    FROM class_subjects cs
    JOIN students st ON st.classes_id = cs.class_id
    WHERE cs.school_id = $1
      AND cs.teacher_id = $2
      AND st.id = $3
)
`

type TeacherTeachesStudentParams struct {
	SchoolID  int32
	TeacherID int32
	ID        int32
}

func (q *Queries) TeacherTeachesStudent(ctx context.Context, arg TeacherTeachesStudentParams) (bool, error) {
	row := q.db.QueryRow(ctx, teacherTeachesStudent, arg.SchoolID, arg.TeacherID, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
