// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scope.sql

package db_queries

import (
	"context"
)

const checkPermission = `-- name: CheckPermission :one
SELECT EXISTS (SELECT 1 FROM permissions p JOIN permission_type pt ON pt.id = p.permission_id WHERE (pt.name = $1 OR pt.name = 'PRINCIPAL') AND p.teacher_id = $2 AND p.school_id = $3)
`

type CheckPermissionParams struct {
	Name      string
	TeacherID int32
	SchoolID  int32
}

func (q *Queries) CheckPermission(ctx context.Context, arg CheckPermissionParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkPermission, arg.Name, arg.TeacherID, arg.SchoolID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isTeacherSchoolMember = `-- name: IsTeacherSchoolMember :one
SELECT EXISTS (SELECT 1 from teacher_school WHERE teacher_id = $1 AND school_id = $2)
`

type IsTeacherSchoolMemberParams struct {
	TeacherID int32
	SchoolID  int32
}

func (q *Queries) IsTeacherSchoolMember(ctx context.Context, arg IsTeacherSchoolMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isTeacherSchoolMember, arg.TeacherID, arg.SchoolID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
