// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db_queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (id, account_uuid, created_at, last_seen_at) VALUES ($1, $2, current_date, current_date)
`

type CreateSessionParams struct {
	ID          pgtype.UUID
	AccountUuid pgtype.UUID
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession, arg.ID, arg.AccountUuid)
	return err
}

const listSessions = `-- name: ListSessions :many
SELECT id, account_uuid, created_at, last_seen_at FROM sessions WHERE account_uuid = $1
`

func (q *Queries) ListSessions(ctx context.Context, accountUuid pgtype.UUID) ([]Session, error) {
	rows, err := q.db.Query(ctx, listSessions, accountUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.AccountUuid,
			&i.CreatedAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeSession = `-- name: RevokeSession :exec
DELETE FROM sessions WHERE id = $1 AND account_uuid = $2
`

type RevokeSessionParams struct {
	ID          pgtype.UUID
	AccountUuid pgtype.UUID
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) error {
	_, err := q.db.Exec(ctx, revokeSession, arg.ID, arg.AccountUuid)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_seen_at = current_date WHERE id = $1
`

func (q *Queries) TouchSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchSession, id)
	return err
}
