// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: status.sql

package db_queries

import (
	"context"
)

const canViewStudent = `-- name: CanViewStudent :one
SELECT 1 FROM guardians_access WHERE guardian_id = $1 AND student_id = $2
`

type CanViewStudentParams struct {
	GuardianID int32
	StudentID  int32
}

func (q *Queries) CanViewStudent(ctx context.Context, arg CanViewStudentParams) (int32, error) {
	row := q.db.QueryRow(ctx, canViewStudent, arg.GuardianID, arg.StudentID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getGuardianChildren = `-- name: GetGuardianChildren :many
SELECT
    s.id,
    s.first_name,
    s.last_name,
    s.school_id,
    s.classes_id AS class_id
FROM guardians_access ga
JOIN students s ON s.id = ga.student_id
WHERE ga.guardian_id = $1
ORDER BY s.last_name, s.first_name
`

type GetGuardianChildrenRow struct {
	ID        int32
	FirstName string
	LastName  string
	SchoolID  int32
	ClassID   int32
}

func (q *Queries) GetGuardianChildren(ctx context.Context, guardianID int32) ([]GetGuardianChildrenRow, error) {
	rows, err := q.db.Query(ctx, getGuardianChildren, guardianID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGuardianChildrenRow
	for rows.Next() {
		var i GetGuardianChildrenRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.SchoolID,
			&i.ClassID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
