// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: students.sql

package db_queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStudent = `-- name: CreateStudent :one
INSERT INTO students (phone_number,first_name,last_name,birth_first_name,birth_last_name,birth_date,birth_city,birth_country,mother_birth_first_name,mother_birth_last_name,permament_address,temporary_address,tax_number,ssn_number,bank_name,iban_owner,iban_number,document_type,document_number) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19) RETURNING id
`

type CreateStudentParams struct {
	PhoneNumber          pgtype.Text
	FirstName            string
	LastName             string
	BirthFirstName       string
	BirthLastName        string
	BirthDate            pgtype.Date
	BirthCity            string
	BirthCountry         string
	MotherBirthFirstName string
	MotherBirthLastName  string
	PermamentAddress     string
	TemporaryAddress     string
	TaxNumber            pgtype.Int4
	SsnNumber            int32
	BankName             string
	IbanOwner            string
	IbanNumber           string
	DocumentType         string
	DocumentNumber       string
}

func (q *Queries) CreateStudent(ctx context.Context, arg CreateStudentParams) (int32, error) {
	row := q.db.QueryRow(ctx, createStudent,
		arg.PhoneNumber,
		arg.FirstName,
		arg.LastName,
		arg.BirthFirstName,
		arg.BirthLastName,
		arg.BirthDate,
		arg.BirthCity,
		arg.BirthCountry,
		arg.MotherBirthFirstName,
		arg.MotherBirthLastName,
		arg.PermamentAddress,
		arg.TemporaryAddress,
		arg.TaxNumber,
		arg.SsnNumber,
		arg.BankName,
		arg.IbanOwner,
		arg.IbanNumber,
		arg.DocumentType,
		arg.DocumentNumber,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getStudent = `-- name: GetStudent :one
SELECT id, phone_number, first_name, last_name, birth_first_name, birth_last_name, birth_date, birth_city, birth_country, mother_birth_first_name, mother_birth_last_name, permament_address, temporary_address, tax_number, ssn_number, bank_name, iban_owner, iban_number, document_type, document_number FROM students WHERE id = $1
`

func (q *Queries) GetStudent(ctx context.Context, id int32) (Student, error) {
	row := q.db.QueryRow(ctx, getStudent, id)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.PhoneNumber,
		&i.FirstName,
		&i.LastName,
		&i.BirthFirstName,
		&i.BirthLastName,
		&i.BirthDate,
		&i.BirthCity,
		&i.BirthCountry,
		&i.MotherBirthFirstName,
		&i.MotherBirthLastName,
		&i.PermamentAddress,
		&i.TemporaryAddress,
		&i.TaxNumber,
		&i.SsnNumber,
		&i.BankName,
		&i.IbanOwner,
		&i.IbanNumber,
		&i.DocumentType,
		&i.DocumentNumber,
	)
	return i, err
}
