// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: students.sql

package db_queries

import (
	"context"
)

const getStudent = `-- name: GetStudent :one
SELECT id, id_number, school_id, phone_number, email_address, first_name, last_name, birth_first_name, birth_last_name, birth_date, birth_city, birth_country, mother_birth_first_name, mother_birth_last_name, classes_id, permament_address, temporary_address, tax_number, ssn_number, bank_name, iban_owner, iban_number, document_type, document_number, password_hash, password_salt FROM students WHERE id = $1
`

func (q *Queries) GetStudent(ctx context.Context, id int32) (Student, error) {
	row := q.db.QueryRow(ctx, getStudent, id)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.IDNumber,
		&i.SchoolID,
		&i.PhoneNumber,
		&i.EmailAddress,
		&i.FirstName,
		&i.LastName,
		&i.BirthFirstName,
		&i.BirthLastName,
		&i.BirthDate,
		&i.BirthCity,
		&i.BirthCountry,
		&i.MotherBirthFirstName,
		&i.MotherBirthLastName,
		&i.ClassesID,
		&i.PermamentAddress,
		&i.TemporaryAddress,
		&i.TaxNumber,
		&i.SsnNumber,
		&i.BankName,
		&i.IbanOwner,
		&i.IbanNumber,
		&i.DocumentType,
		&i.DocumentNumber,
		&i.PasswordHash,
		&i.PasswordSalt,
	)
	return i, err
}

const listStudents = `-- name: ListStudents :many
SELECT id, id_number, school_id, phone_number, email_address, first_name, last_name, birth_first_name, birth_last_name, birth_date, birth_city, birth_country, mother_birth_first_name, mother_birth_last_name, classes_id, permament_address, temporary_address, tax_number, ssn_number, bank_name, iban_owner, iban_number, document_type, document_number, password_hash, password_salt FROM students ORDER BY id
`

func (q *Queries) ListStudents(ctx context.Context) ([]Student, error) {
	rows, err := q.db.Query(ctx, listStudents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Student
	for rows.Next() {
		var i Student
		if err := rows.Scan(
			&i.ID,
			&i.IDNumber,
			&i.SchoolID,
			&i.PhoneNumber,
			&i.EmailAddress,
			&i.FirstName,
			&i.LastName,
			&i.BirthFirstName,
			&i.BirthLastName,
			&i.BirthDate,
			&i.BirthCity,
			&i.BirthCountry,
			&i.MotherBirthFirstName,
			&i.MotherBirthLastName,
			&i.ClassesID,
			&i.PermamentAddress,
			&i.TemporaryAddress,
			&i.TaxNumber,
			&i.SsnNumber,
			&i.BankName,
			&i.IbanOwner,
			&i.IbanNumber,
			&i.DocumentType,
			&i.DocumentNumber,
			&i.PasswordHash,
			&i.PasswordSalt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
