// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: student_school.sql

package db_queries

import (
	"context"
)

const createStudentMembership = `-- name: CreateStudentMembership :one
INSERT INTO student_school (student_id, school_id, classes_id, id_number)
SELECT $1, $2, $3, $4
WHERE EXISTS (
    SELECT 1
    FROM classes c
    WHERE c.id = $3
      AND c.school_id = $2
)
RETURNING id
`

type CreateStudentMembershipParams struct {
	StudentID int32
	SchoolID  int32
	ClassesID int32
	IDNumber  int32
}

func (q *Queries) CreateStudentMembership(ctx context.Context, arg CreateStudentMembershipParams) (int32, error) {
	row := q.db.QueryRow(ctx, createStudentMembership,
		arg.StudentID,
		arg.SchoolID,
		arg.ClassesID,
		arg.IDNumber,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const deleteStudentMembership = `-- name: DeleteStudentMembership :execrows
DELETE FROM student_school WHERE student_id = $1 AND school_id = $2
`

type DeleteStudentMembershipParams struct {
	StudentID int32
	SchoolID  int32
}

func (q *Queries) DeleteStudentMembership(ctx context.Context, arg DeleteStudentMembershipParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStudentMembership, arg.StudentID, arg.SchoolID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getStudentMembership = `-- name: GetStudentMembership :one
SELECT id, student_id, school_id, classes_id, id_number FROM student_school WHERE student_id = $1 AND school_id = $2
`

type GetStudentMembershipParams struct {
	StudentID int32
	SchoolID  int32
}

func (q *Queries) GetStudentMembership(ctx context.Context, arg GetStudentMembershipParams) (StudentSchool, error) {
	row := q.db.QueryRow(ctx, getStudentMembership, arg.StudentID, arg.SchoolID)
	var i StudentSchool
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.SchoolID,
		&i.ClassesID,
		&i.IDNumber,
	)
	return i, err
}

const listStudentMemberships = `-- name: ListStudentMemberships :many
SELECT ss.id, student_id, school_id, classes_id, id_number, school.id, name, zip_code, city, address_line, school_type, principal_id, phone_number, email_address, school.name AS school_name FROM student_school ss
JOIN schools school ON school.id = ss.school_id
WHERE student_id = $1
ORDER BY school_id
`

type ListStudentMembershipsRow struct {
	ID           int32
	StudentID    int32
	SchoolID     int32
	ClassesID    int32
	IDNumber     int32
	ID_2         int32
	Name         string
	ZipCode      string
	City         string
	AddressLine  string
	SchoolType   int32
	PrincipalID  int32
	PhoneNumber  string
	EmailAddress string
	SchoolName   string
}

func (q *Queries) ListStudentMemberships(ctx context.Context, studentID int32) ([]ListStudentMembershipsRow, error) {
	rows, err := q.db.Query(ctx, listStudentMemberships, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStudentMembershipsRow
	for rows.Next() {
		var i ListStudentMembershipsRow
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.SchoolID,
			&i.ClassesID,
			&i.IDNumber,
			&i.ID_2,
			&i.Name,
			&i.ZipCode,
			&i.City,
			&i.AddressLine,
			&i.SchoolType,
			&i.PrincipalID,
			&i.PhoneNumber,
			&i.EmailAddress,
			&i.SchoolName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentMembershipsBySchool = `-- name: ListStudentMembershipsBySchool :many
SELECT
    ss.id,
    ss.student_id,
    ss.school_id,
    ss.classes_id,
    ss.id_number,
    s.first_name,
    s.last_name
FROM student_school ss
JOIN students s ON s.id = ss.student_id
WHERE ss.school_id = $1
ORDER BY s.last_name, s.first_name, ss.school_id
`

type ListStudentMembershipsBySchoolRow struct {
	ID        int32
	StudentID int32
	SchoolID  int32
	ClassesID int32
	IDNumber  int32
	FirstName string
	LastName  string
}

func (q *Queries) ListStudentMembershipsBySchool(ctx context.Context, schoolID int32) ([]ListStudentMembershipsBySchoolRow, error) {
	rows, err := q.db.Query(ctx, listStudentMembershipsBySchool, schoolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStudentMembershipsBySchoolRow
	for rows.Next() {
		var i ListStudentMembershipsBySchoolRow
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.SchoolID,
			&i.ClassesID,
			&i.IDNumber,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
