// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: teachers.sql

package db_queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTeacher = `-- name: CreateTeacher :one
INSERT INTO teachers (phone_number,birth_first_name,birth_last_name,birth_date,birth_city,birth_country,permament_address,temporary_address,first_name,last_name) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) RETURNING id
`

type CreateTeacherParams struct {
	PhoneNumber      string
	BirthFirstName   string
	BirthLastName    string
	BirthDate        pgtype.Date
	BirthCity        string
	BirthCountry     string
	PermamentAddress string
	TemporaryAddress string
	FirstName        string
	LastName         string
}

func (q *Queries) CreateTeacher(ctx context.Context, arg CreateTeacherParams) (int32, error) {
	row := q.db.QueryRow(ctx, createTeacher,
		arg.PhoneNumber,
		arg.BirthFirstName,
		arg.BirthLastName,
		arg.BirthDate,
		arg.BirthCity,
		arg.BirthCountry,
		arg.PermamentAddress,
		arg.TemporaryAddress,
		arg.FirstName,
		arg.LastName,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getTeacher = `-- name: GetTeacher :one
SELECT id, phone_number, birth_first_name, birth_last_name, birth_date, birth_city, birth_country, permament_address, temporary_address, first_name, last_name FROM teachers WHERE id = $1
`

func (q *Queries) GetTeacher(ctx context.Context, id int32) (Teacher, error) {
	row := q.db.QueryRow(ctx, getTeacher, id)
	var i Teacher
	err := row.Scan(
		&i.ID,
		&i.PhoneNumber,
		&i.BirthFirstName,
		&i.BirthLastName,
		&i.BirthDate,
		&i.BirthCity,
		&i.BirthCountry,
		&i.PermamentAddress,
		&i.TemporaryAddress,
		&i.FirstName,
		&i.LastName,
	)
	return i, err
}

const listTeacherSchoolMemberships = `-- name: ListTeacherSchoolMemberships :many
SELECT ts.id, teacher_id, school_id, school.id, name, zip_code, city, address_line, school_type, principal_id, phone_number, email_address, school.name AS school_name FROM teacher_school ts
JOIN schools school ON school.id = ts.school_id
WHERE teacher_id = $1
`

type ListTeacherSchoolMembershipsRow struct {
	ID           int32
	TeacherID    int32
	SchoolID     int32
	ID_2         int32
	Name         string
	ZipCode      string
	City         string
	AddressLine  string
	SchoolType   int32
	PrincipalID  int32
	PhoneNumber  string
	EmailAddress string
	SchoolName   string
}

func (q *Queries) ListTeacherSchoolMemberships(ctx context.Context, teacherID int32) ([]ListTeacherSchoolMembershipsRow, error) {
	rows, err := q.db.Query(ctx, listTeacherSchoolMemberships, teacherID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTeacherSchoolMembershipsRow
	for rows.Next() {
		var i ListTeacherSchoolMembershipsRow
		if err := rows.Scan(
			&i.ID,
			&i.TeacherID,
			&i.SchoolID,
			&i.ID_2,
			&i.Name,
			&i.ZipCode,
			&i.City,
			&i.AddressLine,
			&i.SchoolType,
			&i.PrincipalID,
			&i.PhoneNumber,
			&i.EmailAddress,
			&i.SchoolName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
