// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: themes.sql

package db_queries

import (
	"context"
)

const createTheme = `-- name: CreateTheme :one
INSERT INTO themes (name, colors)
VALUES ($1, $2)
    RETURNING name, colors
`

type CreateThemeParams struct {
	Name   string
	Colors []byte
}

func (q *Queries) CreateTheme(ctx context.Context, arg CreateThemeParams) (Theme, error) {
	row := q.db.QueryRow(ctx, createTheme, arg.Name, arg.Colors)
	var i Theme
	err := row.Scan(&i.Name, &i.Colors)
	return i, err
}

const deleteTheme = `-- name: DeleteTheme :execrows
DELETE FROM themes
WHERE name = $1
`

func (q *Queries) DeleteTheme(ctx context.Context, name string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTheme, name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getThemeByName = `-- name: GetThemeByName :one
SELECT name, colors
FROM themes
WHERE name = $1
`

func (q *Queries) GetThemeByName(ctx context.Context, name string) (Theme, error) {
	row := q.db.QueryRow(ctx, getThemeByName, name)
	var i Theme
	err := row.Scan(&i.Name, &i.Colors)
	return i, err
}

const listThemes = `-- name: ListThemes :many
SELECT name, colors
FROM themes
ORDER BY name ASC
`

func (q *Queries) ListThemes(ctx context.Context) ([]Theme, error) {
	rows, err := q.db.Query(ctx, listThemes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Theme
	for rows.Next() {
		var i Theme
		if err := rows.Scan(&i.Name, &i.Colors); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTheme = `-- name: UpdateTheme :one
UPDATE themes
SET colors = $2
WHERE name = $1
    RETURNING name, colors
`

type UpdateThemeParams struct {
	Name   string
	Colors []byte
}

func (q *Queries) UpdateTheme(ctx context.Context, arg UpdateThemeParams) (Theme, error) {
	row := q.db.QueryRow(ctx, updateTheme, arg.Name, arg.Colors)
	var i Theme
	err := row.Scan(&i.Name, &i.Colors)
	return i, err
}
