// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: themes.sql

package db_queries

import (
	"context"
)

const deleteTheme = `-- name: DeleteTheme :execrows
DELETE FROM themes
WHERE name = $1
`

func (q *Queries) DeleteTheme(ctx context.Context, name string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTheme, name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getThemeByName = `-- name: GetThemeByName :one
SELECT name, colors
FROM themes
WHERE name = $1
`

func (q *Queries) GetThemeByName(ctx context.Context, name string) (Theme, error) {
	row := q.db.QueryRow(ctx, getThemeByName, name)
	var i Theme
	err := row.Scan(&i.Name, &i.Colors)
	return i, err
}

const listThemes = `-- name: ListThemes :many
SELECT name, colors
FROM themes
ORDER BY name ASC
`

func (q *Queries) ListThemes(ctx context.Context) ([]Theme, error) {
	rows, err := q.db.Query(ctx, listThemes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Theme
	for rows.Next() {
		var i Theme
		if err := rows.Scan(&i.Name, &i.Colors); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTheme = `-- name: UpsertTheme :one
INSERT INTO themes (name, colors)
VALUES ($1, $2)
    ON CONFLICT (name)
DO UPDATE SET colors = EXCLUDED.colors
           RETURNING name, colors
`

type UpsertThemeParams struct {
	Name   string
	Colors []byte
}

func (q *Queries) UpsertTheme(ctx context.Context, arg UpsertThemeParams) (Theme, error) {
	row := q.db.QueryRow(ctx, upsertTheme, arg.Name, arg.Colors)
	var i Theme
	err := row.Scan(&i.Name, &i.Colors)
	return i, err
}
