// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: timetable.sql

package db_queries

import (
	"context"
)

const createBellScheduleType = `-- name: CreateBellScheduleType :exec
INSERT INTO bell_schedule_type (school_id, name) VALUES ($1, $2)
`

type CreateBellScheduleTypeParams struct {
	SchoolID int32
	Name     string
}

func (q *Queries) CreateBellScheduleType(ctx context.Context, arg CreateBellScheduleTypeParams) error {
	_, err := q.db.Exec(ctx, createBellScheduleType, arg.SchoolID, arg.Name)
	return err
}

const createCustomSubject = `-- name: CreateCustomSubject :exec
INSERT INTO custom_subjects (school_id, subject_name) VALUES ($1, $2)
`

type CreateCustomSubjectParams struct {
	SchoolID    int32
	SubjectName string
}

func (q *Queries) CreateCustomSubject(ctx context.Context, arg CreateCustomSubjectParams) error {
	_, err := q.db.Exec(ctx, createCustomSubject, arg.SchoolID, arg.SubjectName)
	return err
}

const deleteBellScheduleType = `-- name: DeleteBellScheduleType :exec
DELETE FROM bell_schedule_type WHERE school_id = $1 AND id = $2
`

type DeleteBellScheduleTypeParams struct {
	SchoolID int32
	ID       int32
}

func (q *Queries) DeleteBellScheduleType(ctx context.Context, arg DeleteBellScheduleTypeParams) error {
	_, err := q.db.Exec(ctx, deleteBellScheduleType, arg.SchoolID, arg.ID)
	return err
}

const deleteCustomSubject = `-- name: DeleteCustomSubject :exec
DELETE FROM custom_subjects WHERE school_id = $1 AND id = $2
`

type DeleteCustomSubjectParams struct {
	SchoolID int32
	ID       int32
}

func (q *Queries) DeleteCustomSubject(ctx context.Context, arg DeleteCustomSubjectParams) error {
	_, err := q.db.Exec(ctx, deleteCustomSubject, arg.SchoolID, arg.ID)
	return err
}

const editBellScheduleType = `-- name: EditBellScheduleType :exec
UPDATE bell_schedule_type SET name = $1 WHERE id = $2 AND school_id = $3
`

type EditBellScheduleTypeParams struct {
	Name     string
	ID       int32
	SchoolID int32
}

func (q *Queries) EditBellScheduleType(ctx context.Context, arg EditBellScheduleTypeParams) error {
	_, err := q.db.Exec(ctx, editBellScheduleType, arg.Name, arg.ID, arg.SchoolID)
	return err
}

const editCustomSubject = `-- name: EditCustomSubject :exec
UPDATE custom_subjects SET subject_name = $1 WHERE school_id = $2 AND id = $3
`

type EditCustomSubjectParams struct {
	SubjectName string
	SchoolID    int32
	ID          int32
}

func (q *Queries) EditCustomSubject(ctx context.Context, arg EditCustomSubjectParams) error {
	_, err := q.db.Exec(ctx, editCustomSubject, arg.SubjectName, arg.SchoolID, arg.ID)
	return err
}

const readBellScheduleType = `-- name: ReadBellScheduleType :many
SELECT id, name FROM bell_schedule_type WHERE school_id = $1
`

type ReadBellScheduleTypeRow struct {
	ID   int32
	Name string
}

func (q *Queries) ReadBellScheduleType(ctx context.Context, schoolID int32) ([]ReadBellScheduleTypeRow, error) {
	rows, err := q.db.Query(ctx, readBellScheduleType, schoolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReadBellScheduleTypeRow
	for rows.Next() {
		var i ReadBellScheduleTypeRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readCustomSubject = `-- name: ReadCustomSubject :many
SELECT id, subject_name FROM custom_subjects WHERE school_id = $1
`

type ReadCustomSubjectRow struct {
	ID          int32
	SubjectName string
}

func (q *Queries) ReadCustomSubject(ctx context.Context, schoolID int32) ([]ReadCustomSubjectRow, error) {
	rows, err := q.db.Query(ctx, readCustomSubject, schoolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReadCustomSubjectRow
	for rows.Next() {
		var i ReadCustomSubjectRow
		if err := rows.Scan(&i.ID, &i.SubjectName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
