// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: timetable.sql

package db_queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addCanceledLesson = `-- name: AddCanceledLesson :exec
INSERT INTO time_table (school_id, teacher_id, room_id, day_of_week, group_id, custom_subject, custom_subject_id, subject_id, actual_date, lesson_num, canceled) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, true) ON CONFLICT (school_id, room_id, actual_date, lesson_num, group_id) DO UPDATE SET canceled = true
`

type AddCanceledLessonParams struct {
	SchoolID        int32
	TeacherID       int32
	RoomID          int32
	DayOfWeek       int32
	GroupID         int32
	CustomSubject   bool
	CustomSubjectID pgtype.Int4
	SubjectID       pgtype.Int4
	ActualDate      pgtype.Date
	LessonNum       int32
}

func (q *Queries) AddCanceledLesson(ctx context.Context, arg AddCanceledLessonParams) error {
	_, err := q.db.Exec(ctx, addCanceledLesson,
		arg.SchoolID,
		arg.TeacherID,
		arg.RoomID,
		arg.DayOfWeek,
		arg.GroupID,
		arg.CustomSubject,
		arg.CustomSubjectID,
		arg.SubjectID,
		arg.ActualDate,
		arg.LessonNum,
	)
	return err
}

const createBaseSchedule = `-- name: CreateBaseSchedule :exec
INSERT INTO base_schedule (school_id, teacher_id, room_id, day_of_week, lesson_num, group_id, custom_subject, subject_id, custom_subject_id) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateBaseScheduleParams struct {
	SchoolID        int32
	TeacherID       int32
	RoomID          int32
	DayOfWeek       int32
	LessonNum       int32
	GroupID         int32
	CustomSubject   bool
	SubjectID       pgtype.Int4
	CustomSubjectID pgtype.Int4
}

func (q *Queries) CreateBaseSchedule(ctx context.Context, arg CreateBaseScheduleParams) error {
	_, err := q.db.Exec(ctx, createBaseSchedule,
		arg.SchoolID,
		arg.TeacherID,
		arg.RoomID,
		arg.DayOfWeek,
		arg.LessonNum,
		arg.GroupID,
		arg.CustomSubject,
		arg.SubjectID,
		arg.CustomSubjectID,
	)
	return err
}

const createBellScheduleType = `-- name: CreateBellScheduleType :exec
INSERT INTO bell_schedule_type (school_id, name) VALUES ($1, $2)
`

type CreateBellScheduleTypeParams struct {
	SchoolID int32
	Name     string
}

func (q *Queries) CreateBellScheduleType(ctx context.Context, arg CreateBellScheduleTypeParams) error {
	_, err := q.db.Exec(ctx, createBellScheduleType, arg.SchoolID, arg.Name)
	return err
}

const createCustomSubject = `-- name: CreateCustomSubject :exec
INSERT INTO custom_subjects (school_id, subject_name) VALUES ($1, $2)
`

type CreateCustomSubjectParams struct {
	SchoolID    int32
	SubjectName string
}

func (q *Queries) CreateCustomSubject(ctx context.Context, arg CreateCustomSubjectParams) error {
	_, err := q.db.Exec(ctx, createCustomSubject, arg.SchoolID, arg.SubjectName)
	return err
}

const createGroup = `-- name: CreateGroup :exec
INSERT INTO groups (school_id, bell_id, group_name) VALUES ($1, $2, $3)
`

type CreateGroupParams struct {
	SchoolID  int32
	BellID    int32
	GroupName string
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) error {
	_, err := q.db.Exec(ctx, createGroup, arg.SchoolID, arg.BellID, arg.GroupName)
	return err
}

const createLessonTime = `-- name: CreateLessonTime :exec
INSERT INTO bell_schedule (school_id, type_id, lesson_number, at_start, at_end) VALUES ($1, $2, $3, $4, $5)
`

type CreateLessonTimeParams struct {
	SchoolID     int32
	TypeID       int32
	LessonNumber pgtype.Int4
	AtStart      pgtype.Time
	AtEnd        pgtype.Time
}

func (q *Queries) CreateLessonTime(ctx context.Context, arg CreateLessonTimeParams) error {
	_, err := q.db.Exec(ctx, createLessonTime,
		arg.SchoolID,
		arg.TypeID,
		arg.LessonNumber,
		arg.AtStart,
		arg.AtEnd,
	)
	return err
}

const createRealTimeLesson = `-- name: CreateRealTimeLesson :exec
INSERT INTO time_table (school_id, teacher_id, room_id, day_of_week, group_id, custom_subject, custom_subject_id, subject_id, actual_date, lesson_num) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type CreateRealTimeLessonParams struct {
	SchoolID        int32
	TeacherID       int32
	RoomID          int32
	DayOfWeek       int32
	GroupID         int32
	CustomSubject   bool
	CustomSubjectID pgtype.Int4
	SubjectID       pgtype.Int4
	ActualDate      pgtype.Date
	LessonNum       int32
}

func (q *Queries) CreateRealTimeLesson(ctx context.Context, arg CreateRealTimeLessonParams) error {
	_, err := q.db.Exec(ctx, createRealTimeLesson,
		arg.SchoolID,
		arg.TeacherID,
		arg.RoomID,
		arg.DayOfWeek,
		arg.GroupID,
		arg.CustomSubject,
		arg.CustomSubjectID,
		arg.SubjectID,
		arg.ActualDate,
		arg.LessonNum,
	)
	return err
}

const createRoom = `-- name: CreateRoom :exec
INSERT INTO rooms (school_id, name, capacity) VALUES ($1, $2, $3)
`

type CreateRoomParams struct {
	SchoolID int32
	Name     string
	Capacity int32
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) error {
	_, err := q.db.Exec(ctx, createRoom, arg.SchoolID, arg.Name, arg.Capacity)
	return err
}

const deleteBaseSchedule = `-- name: DeleteBaseSchedule :exec
DELETE FROM base_schedule WHERE id = $1 AND school_id = $2
`

type DeleteBaseScheduleParams struct {
	ID       int32
	SchoolID int32
}

func (q *Queries) DeleteBaseSchedule(ctx context.Context, arg DeleteBaseScheduleParams) error {
	_, err := q.db.Exec(ctx, deleteBaseSchedule, arg.ID, arg.SchoolID)
	return err
}

const deleteBellScheduleType = `-- name: DeleteBellScheduleType :exec
DELETE FROM bell_schedule_type WHERE school_id = $1 AND id = $2
`

type DeleteBellScheduleTypeParams struct {
	SchoolID int32
	ID       int32
}

func (q *Queries) DeleteBellScheduleType(ctx context.Context, arg DeleteBellScheduleTypeParams) error {
	_, err := q.db.Exec(ctx, deleteBellScheduleType, arg.SchoolID, arg.ID)
	return err
}

const deleteCustomSubject = `-- name: DeleteCustomSubject :exec
DELETE FROM custom_subjects WHERE school_id = $1 AND id = $2
`

type DeleteCustomSubjectParams struct {
	SchoolID int32
	ID       int32
}

func (q *Queries) DeleteCustomSubject(ctx context.Context, arg DeleteCustomSubjectParams) error {
	_, err := q.db.Exec(ctx, deleteCustomSubject, arg.SchoolID, arg.ID)
	return err
}

const deleteGroup = `-- name: DeleteGroup :exec
DELETE FROM groups WHERE school_id = $1 AND id = $2
`

type DeleteGroupParams struct {
	SchoolID int32
	ID       int32
}

func (q *Queries) DeleteGroup(ctx context.Context, arg DeleteGroupParams) error {
	_, err := q.db.Exec(ctx, deleteGroup, arg.SchoolID, arg.ID)
	return err
}

const deleteLessonTime = `-- name: DeleteLessonTime :exec
DELETE FROM bell_schedule WHERE school_id = $1 AND id = $2
`

type DeleteLessonTimeParams struct {
	SchoolID int32
	ID       int32
}

func (q *Queries) DeleteLessonTime(ctx context.Context, arg DeleteLessonTimeParams) error {
	_, err := q.db.Exec(ctx, deleteLessonTime, arg.SchoolID, arg.ID)
	return err
}

const deleteRealTimeLesson = `-- name: DeleteRealTimeLesson :exec
DELETE FROM time_table WHERE school_id = $1 AND id = $2
`

type DeleteRealTimeLessonParams struct {
	SchoolID int32
	ID       int32
}

func (q *Queries) DeleteRealTimeLesson(ctx context.Context, arg DeleteRealTimeLessonParams) error {
	_, err := q.db.Exec(ctx, deleteRealTimeLesson, arg.SchoolID, arg.ID)
	return err
}

const deleteRoom = `-- name: DeleteRoom :exec
DELETE FROM rooms WHERE school_id = $1 AND id = $2
`

type DeleteRoomParams struct {
	SchoolID int32
	ID       int32
}

func (q *Queries) DeleteRoom(ctx context.Context, arg DeleteRoomParams) error {
	_, err := q.db.Exec(ctx, deleteRoom, arg.SchoolID, arg.ID)
	return err
}

const deleteStudentFromGroup = `-- name: DeleteStudentFromGroup :exec
DELETE FROM group_members WHERE group_id = $1 AND student_id = $2 AND school_id = $3
`

type DeleteStudentFromGroupParams struct {
	GroupID   int32
	StudentID int32
	SchoolID  int32
}

func (q *Queries) DeleteStudentFromGroup(ctx context.Context, arg DeleteStudentFromGroupParams) error {
	_, err := q.db.Exec(ctx, deleteStudentFromGroup, arg.GroupID, arg.StudentID, arg.SchoolID)
	return err
}

const editBellScheduleType = `-- name: EditBellScheduleType :exec
UPDATE bell_schedule_type SET name = $1 WHERE id = $2 AND school_id = $3
`

type EditBellScheduleTypeParams struct {
	Name     string
	ID       int32
	SchoolID int32
}

func (q *Queries) EditBellScheduleType(ctx context.Context, arg EditBellScheduleTypeParams) error {
	_, err := q.db.Exec(ctx, editBellScheduleType, arg.Name, arg.ID, arg.SchoolID)
	return err
}

const editCustomSubject = `-- name: EditCustomSubject :exec
UPDATE custom_subjects SET subject_name = $1 WHERE school_id = $2 AND id = $3
`

type EditCustomSubjectParams struct {
	SubjectName string
	SchoolID    int32
	ID          int32
}

func (q *Queries) EditCustomSubject(ctx context.Context, arg EditCustomSubjectParams) error {
	_, err := q.db.Exec(ctx, editCustomSubject, arg.SubjectName, arg.SchoolID, arg.ID)
	return err
}

const editGroup = `-- name: EditGroup :exec
UPDATE groups SET group_name = $1 WHERE school_id = $2 AND id = $3
`

type EditGroupParams struct {
	GroupName string
	SchoolID  int32
	ID        int32
}

func (q *Queries) EditGroup(ctx context.Context, arg EditGroupParams) error {
	_, err := q.db.Exec(ctx, editGroup, arg.GroupName, arg.SchoolID, arg.ID)
	return err
}

const editLessonTime = `-- name: EditLessonTime :exec
UPDATE bell_schedule set lesson_number = $1, at_start = $2, at_end = $3 WHERE id = $4 AND school_id = $5
`

type EditLessonTimeParams struct {
	LessonNumber pgtype.Int4
	AtStart      pgtype.Time
	AtEnd        pgtype.Time
	ID           int32
	SchoolID     int32
}

func (q *Queries) EditLessonTime(ctx context.Context, arg EditLessonTimeParams) error {
	_, err := q.db.Exec(ctx, editLessonTime,
		arg.LessonNumber,
		arg.AtStart,
		arg.AtEnd,
		arg.ID,
		arg.SchoolID,
	)
	return err
}

const editRoom = `-- name: EditRoom :exec
UPDATE rooms SET name = $1, capacity = $2 WHERE school_id = $3 AND id = $4
`

type EditRoomParams struct {
	Name     string
	Capacity int32
	SchoolID int32
	ID       int32
}

func (q *Queries) EditRoom(ctx context.Context, arg EditRoomParams) error {
	_, err := q.db.Exec(ctx, editRoom,
		arg.Name,
		arg.Capacity,
		arg.SchoolID,
		arg.ID,
	)
	return err
}

const insertStudentToGroup = `-- name: InsertStudentToGroup :exec
INSERT INTO group_members (school_id, group_id, student_id) VALUES ($1, $2, $3)
`

type InsertStudentToGroupParams struct {
	SchoolID  int32
	GroupID   int32
	StudentID int32
}

func (q *Queries) InsertStudentToGroup(ctx context.Context, arg InsertStudentToGroupParams) error {
	_, err := q.db.Exec(ctx, insertStudentToGroup, arg.SchoolID, arg.GroupID, arg.StudentID)
	return err
}

const manageSubsitutionLesson = `-- name: ManageSubsitutionLesson :exec
UPDATE time_table SET teacher_id = $2, room_id = $3, day_of_week = $4, group_id = $5, custom_subject = $6, custom_subject_id = $7, subject_id = $8, actual_date = $9, lesson_num = $10, is_substitution = $11, substitution_teacher_id = $12 WHERE school_id = $1 AND id = $13
`

type ManageSubsitutionLessonParams struct {
	SchoolID              int32
	TeacherID             int32
	RoomID                int32
	DayOfWeek             int32
	GroupID               int32
	CustomSubject         bool
	CustomSubjectID       pgtype.Int4
	SubjectID             pgtype.Int4
	ActualDate            pgtype.Date
	LessonNum             int32
	IsSubstitution        bool
	SubstitutionTeacherID pgtype.Int4
	ID                    int32
}

func (q *Queries) ManageSubsitutionLesson(ctx context.Context, arg ManageSubsitutionLessonParams) error {
	_, err := q.db.Exec(ctx, manageSubsitutionLesson,
		arg.SchoolID,
		arg.TeacherID,
		arg.RoomID,
		arg.DayOfWeek,
		arg.GroupID,
		arg.CustomSubject,
		arg.CustomSubjectID,
		arg.SubjectID,
		arg.ActualDate,
		arg.LessonNum,
		arg.IsSubstitution,
		arg.SubstitutionTeacherID,
		arg.ID,
	)
	return err
}

const readBaseScheduleClass = `-- name: ReadBaseScheduleClass :many
SELECT DISTINCT bs.id, bs.school_id, bs.teacher_id, bs.room_id, bs.day_of_week, bs.lesson_num, bs.group_id, bs.custom_subject, bs.subject_id, bs.custom_subject_id FROM base_schedule bs JOIN groups g ON bs.group_id = g.id JOIN group_members gm ON g.id = gm.group_id JOIN students s ON gm.student_id = s.id WHERE s.classes_id = $1 AND s.school_id = $2
`

type ReadBaseScheduleClassParams struct {
	ClassesID int32
	SchoolID  int32
}

func (q *Queries) ReadBaseScheduleClass(ctx context.Context, arg ReadBaseScheduleClassParams) ([]BaseSchedule, error) {
	rows, err := q.db.Query(ctx, readBaseScheduleClass, arg.ClassesID, arg.SchoolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BaseSchedule
	for rows.Next() {
		var i BaseSchedule
		if err := rows.Scan(
			&i.ID,
			&i.SchoolID,
			&i.TeacherID,
			&i.RoomID,
			&i.DayOfWeek,
			&i.LessonNum,
			&i.GroupID,
			&i.CustomSubject,
			&i.SubjectID,
			&i.CustomSubjectID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readBaseScheduleGroup = `-- name: ReadBaseScheduleGroup :many
SELECT id, school_id, teacher_id, room_id, day_of_week, lesson_num, group_id, custom_subject, subject_id, custom_subject_id FROM base_schedule WHERE group_id = $1 AND school_id = $2
`

type ReadBaseScheduleGroupParams struct {
	GroupID  int32
	SchoolID int32
}

func (q *Queries) ReadBaseScheduleGroup(ctx context.Context, arg ReadBaseScheduleGroupParams) ([]BaseSchedule, error) {
	rows, err := q.db.Query(ctx, readBaseScheduleGroup, arg.GroupID, arg.SchoolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BaseSchedule
	for rows.Next() {
		var i BaseSchedule
		if err := rows.Scan(
			&i.ID,
			&i.SchoolID,
			&i.TeacherID,
			&i.RoomID,
			&i.DayOfWeek,
			&i.LessonNum,
			&i.GroupID,
			&i.CustomSubject,
			&i.SubjectID,
			&i.CustomSubjectID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readBellScheduleType = `-- name: ReadBellScheduleType :many
SELECT id, name FROM bell_schedule_type WHERE school_id = $1
`

type ReadBellScheduleTypeRow struct {
	ID   int32
	Name string
}

func (q *Queries) ReadBellScheduleType(ctx context.Context, schoolID int32) ([]ReadBellScheduleTypeRow, error) {
	rows, err := q.db.Query(ctx, readBellScheduleType, schoolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReadBellScheduleTypeRow
	for rows.Next() {
		var i ReadBellScheduleTypeRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readCustomSubject = `-- name: ReadCustomSubject :many
SELECT id, subject_name FROM custom_subjects WHERE school_id = $1
`

type ReadCustomSubjectRow struct {
	ID          int32
	SubjectName string
}

func (q *Queries) ReadCustomSubject(ctx context.Context, schoolID int32) ([]ReadCustomSubjectRow, error) {
	rows, err := q.db.Query(ctx, readCustomSubject, schoolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReadCustomSubjectRow
	for rows.Next() {
		var i ReadCustomSubjectRow
		if err := rows.Scan(&i.ID, &i.SubjectName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readGroup = `-- name: ReadGroup :many
SELECT id, school_id, bell_id, group_name FROM groups WHERE school_id = $1
`

func (q *Queries) ReadGroup(ctx context.Context, schoolID int32) ([]Group, error) {
	rows, err := q.db.Query(ctx, readGroup, schoolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.SchoolID,
			&i.BellID,
			&i.GroupName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readLessonTime = `-- name: ReadLessonTime :many
SELECT id, school_id, type_id, lesson_number, at_start, at_end FROM bell_schedule WHERE school_id = $1 AND type_id = $2
`

type ReadLessonTimeParams struct {
	SchoolID int32
	TypeID   int32
}

func (q *Queries) ReadLessonTime(ctx context.Context, arg ReadLessonTimeParams) ([]BellSchedule, error) {
	rows, err := q.db.Query(ctx, readLessonTime, arg.SchoolID, arg.TypeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BellSchedule
	for rows.Next() {
		var i BellSchedule
		if err := rows.Scan(
			&i.ID,
			&i.SchoolID,
			&i.TypeID,
			&i.LessonNumber,
			&i.AtStart,
			&i.AtEnd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readListOfStudents = `-- name: ReadListOfStudents :many
SELECT s.id, s.first_name, s.last_name FROM students AS s INNER JOIN group_members AS g_m ON g_m.student_id = s.id WHERE g_m.group_id = $1 AND g_m.school_id = $2
`

type ReadListOfStudentsParams struct {
	GroupID  int32
	SchoolID int32
}

type ReadListOfStudentsRow struct {
	ID        int32
	FirstName string
	LastName  string
}

func (q *Queries) ReadListOfStudents(ctx context.Context, arg ReadListOfStudentsParams) ([]ReadListOfStudentsRow, error) {
	rows, err := q.db.Query(ctx, readListOfStudents, arg.GroupID, arg.SchoolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReadListOfStudentsRow
	for rows.Next() {
		var i ReadListOfStudentsRow
		if err := rows.Scan(&i.ID, &i.FirstName, &i.LastName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readRealTimeTable = `-- name: ReadRealTimeTable :many
SELECT  COALESCE(t.room_id, b.room_id) AS room_id, COALESCE(t.lesson_num, b.lesson_num) AS lesson_num, COALESCE(t.day_of_week, b.day_of_week) AS day_of_week, COALESCE(t.substitution_teacher_id, t.teacher_id, b.teacher_id) AS effective_teacher_id, COALESCE(t.group_id, b.group_id) AS group_id, COALESCE(t.school_id, b.school_id) AS school_id, COALESCE(t.custom_subject, b.custom_subject) AS custom_subject, COALESCE(t.subject_id, b.subject_id) AS subject_id, COALESCE(t.custom_subject_id, b.custom_subject_id) AS custom_subject_id, COALESCE(t.is_substitution, FALSE) AS is_substitution, COALESCE(t.canceled, FALSE) AS canceled FROM base_schedule b LEFT JOIN time_table t ON t.school_id = b.school_id AND t.group_id = b.group_id AND t.day_of_week = b.day_of_week AND t.lesson_num = b.lesson_num AND t.actual_date BETWEEN $1 AND $2 WHERE b.group_id IN ( SELECT g.id FROM groups g JOIN group_members gm ON g.id = gm.group_id JOIN students s ON gm.student_id = s.id WHERE s.classes_id = $3 AND s.school_id = $4)
`

type ReadRealTimeTableParams struct {
	ActualDate   pgtype.Date
	ActualDate_2 pgtype.Date
	ClassesID    int32
	SchoolID     int32
}

type ReadRealTimeTableRow struct {
	RoomID             int32
	LessonNum          int32
	DayOfWeek          int32
	EffectiveTeacherID int32
	GroupID            int32
	SchoolID           int32
	CustomSubject      bool
	SubjectID          pgtype.Int4
	CustomSubjectID    pgtype.Int4
	IsSubstitution     bool
	Canceled           bool
}

func (q *Queries) ReadRealTimeTable(ctx context.Context, arg ReadRealTimeTableParams) ([]ReadRealTimeTableRow, error) {
	rows, err := q.db.Query(ctx, readRealTimeTable,
		arg.ActualDate,
		arg.ActualDate_2,
		arg.ClassesID,
		arg.SchoolID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReadRealTimeTableRow
	for rows.Next() {
		var i ReadRealTimeTableRow
		if err := rows.Scan(
			&i.RoomID,
			&i.LessonNum,
			&i.DayOfWeek,
			&i.EffectiveTeacherID,
			&i.GroupID,
			&i.SchoolID,
			&i.CustomSubject,
			&i.SubjectID,
			&i.CustomSubjectID,
			&i.IsSubstitution,
			&i.Canceled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readRoom = `-- name: ReadRoom :many
SELECT id, name, capacity FROM rooms WHERE school_id = $1
`

type ReadRoomRow struct {
	ID       int32
	Name     string
	Capacity int32
}

func (q *Queries) ReadRoom(ctx context.Context, schoolID int32) ([]ReadRoomRow, error) {
	rows, err := q.db.Query(ctx, readRoom, schoolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReadRoomRow
	for rows.Next() {
		var i ReadRoomRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Capacity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeCanceledLesson = `-- name: RemoveCanceledLesson :exec
INSERT INTO time_table (school_id, teacher_id, room_id, day_of_week, group_id, custom_subject, custom_subject_id, subject_id, actual_date, lesson_num, canceled) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, false) ON CONFLICT (school_id, room_id, actual_date, lesson_num, group_id) DO UPDATE SET canceled = false
`

type RemoveCanceledLessonParams struct {
	SchoolID        int32
	TeacherID       int32
	RoomID          int32
	DayOfWeek       int32
	GroupID         int32
	CustomSubject   bool
	CustomSubjectID pgtype.Int4
	SubjectID       pgtype.Int4
	ActualDate      pgtype.Date
	LessonNum       int32
}

func (q *Queries) RemoveCanceledLesson(ctx context.Context, arg RemoveCanceledLessonParams) error {
	_, err := q.db.Exec(ctx, removeCanceledLesson,
		arg.SchoolID,
		arg.TeacherID,
		arg.RoomID,
		arg.DayOfWeek,
		arg.GroupID,
		arg.CustomSubject,
		arg.CustomSubjectID,
		arg.SubjectID,
		arg.ActualDate,
		arg.LessonNum,
	)
	return err
}

const updateBaseSchedule = `-- name: UpdateBaseSchedule :exec
UPDATE base_schedule SET teacher_id = $1, day_of_week = $2, lesson_num = $3, room_id = $4, group_id = $5, custom_subject = $6, subject_id = $7, custom_subject_id = $8 WHERE id = $9 AND school_id = $10
`

type UpdateBaseScheduleParams struct {
	TeacherID       int32
	DayOfWeek       int32
	LessonNum       int32
	RoomID          int32
	GroupID         int32
	CustomSubject   bool
	SubjectID       pgtype.Int4
	CustomSubjectID pgtype.Int4
	ID              int32
	SchoolID        int32
}

func (q *Queries) UpdateBaseSchedule(ctx context.Context, arg UpdateBaseScheduleParams) error {
	_, err := q.db.Exec(ctx, updateBaseSchedule,
		arg.TeacherID,
		arg.DayOfWeek,
		arg.LessonNum,
		arg.RoomID,
		arg.GroupID,
		arg.CustomSubject,
		arg.SubjectID,
		arg.CustomSubjectID,
		arg.ID,
		arg.SchoolID,
	)
	return err
}

const updateRealTimeLesson = `-- name: UpdateRealTimeLesson :exec
UPDATE time_table SET teacher_id = $1, room_id = $2, day_of_week = $3, group_id = $4, custom_subject = $5, custom_subject_id = $6, subject_id = $7, actual_date = $8, lesson_num = $9 WHERE school_id = $10 AND id = $11
`

type UpdateRealTimeLessonParams struct {
	TeacherID       int32
	RoomID          int32
	DayOfWeek       int32
	GroupID         int32
	CustomSubject   bool
	CustomSubjectID pgtype.Int4
	SubjectID       pgtype.Int4
	ActualDate      pgtype.Date
	LessonNum       int32
	SchoolID        int32
	ID              int32
}

func (q *Queries) UpdateRealTimeLesson(ctx context.Context, arg UpdateRealTimeLessonParams) error {
	_, err := q.db.Exec(ctx, updateRealTimeLesson,
		arg.TeacherID,
		arg.RoomID,
		arg.DayOfWeek,
		arg.GroupID,
		arg.CustomSubject,
		arg.CustomSubjectID,
		arg.SubjectID,
		arg.ActualDate,
		arg.LessonNum,
		arg.SchoolID,
		arg.ID,
	)
	return err
}
